// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
reg    ap_block_pp0_stage3_subdone;
reg   [15:0] reg_1551;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire    ap_block_pp0_stage3_11001;
wire    ap_block_pp0_stage0_11001;
reg   [15:0] reg_1555;
reg   [15:0] reg_1559;
reg   [15:0] reg_1563;
reg   [15:0] reg_1567;
reg   [15:0] reg_1571;
reg   [15:0] reg_1575;
reg   [15:0] reg_1579;
reg   [14:0] reg_1583;
reg   [15:0] reg_1587;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [15:0] reg_1591;
reg   [15:0] reg_1595;
reg   [14:0] reg_1599;
reg  signed [15:0] data_5_val_read_reg_2219;
reg  signed [15:0] data_3_val_read_reg_2226;
reg  signed [15:0] data_1_val_read_reg_2232;
wire  signed [25:0] sext_ln70_4_fu_1603_p1;
reg  signed [25:0] sext_ln70_4_reg_2237;
wire  signed [21:0] sext_ln70_8_fu_1612_p1;
wire  signed [24:0] sext_ln70_15_fu_1617_p1;
wire  signed [25:0] sext_ln70_17_fu_1622_p1;
wire  signed [21:0] sext_ln70_3_fu_1631_p1;
wire  signed [24:0] sext_ln70_5_fu_1635_p1;
wire  signed [25:0] sext_ln70_6_fu_1640_p1;
wire  signed [25:0] sext_ln70_9_fu_1651_p1;
reg  signed [25:0] sext_ln70_9_reg_2286;
reg   [11:0] trunc_ln42_26_reg_2296;
reg   [15:0] trunc_ln42_39_reg_2301;
reg   [15:0] trunc_ln42_41_reg_2306;
reg  signed [15:0] data_4_val_read_reg_2311;
reg   [15:0] trunc_ln42_12_reg_2317;
reg   [11:0] trunc_ln42_13_reg_2322;
reg   [15:0] trunc_ln42_15_reg_2327;
reg   [15:0] trunc_ln42_16_reg_2332;
reg   [15:0] trunc_ln42_19_reg_2337;
reg   [15:0] trunc_ln42_21_reg_2342;
reg   [15:0] trunc_ln42_22_reg_2347;
wire  signed [24:0] sext_ln70_7_fu_1685_p1;
reg   [15:0] trunc_ln42_23_reg_2357;
wire  signed [25:0] sext_ln70_11_fu_1699_p1;
wire  signed [24:0] sext_ln70_13_fu_1706_p1;
wire  signed [23:0] sext_ln70_14_fu_1711_p1;
wire  signed [24:0] sext_ln70_fu_1717_p1;
wire  signed [23:0] sext_ln70_1_fu_1722_p1;
wire  signed [25:0] sext_ln70_2_fu_1727_p1;
reg   [14:0] trunc_ln42_29_reg_2400;
wire  signed [22:0] sext_ln70_10_fu_1757_p1;
reg   [13:0] trunc_ln42_31_reg_2410;
reg   [13:0] trunc_ln42_37_reg_2415;
wire  signed [23:0] sext_ln70_16_fu_1804_p1;
wire   [15:0] add_ln58_fu_1850_p2;
reg   [15:0] add_ln58_reg_2425;
wire   [15:0] add_ln58_3_fu_1855_p2;
reg   [15:0] add_ln58_3_reg_2430;
wire   [15:0] add_ln58_6_fu_1860_p2;
reg   [15:0] add_ln58_6_reg_2435;
wire   [15:0] add_ln58_9_fu_1865_p2;
reg   [15:0] add_ln58_9_reg_2440;
wire   [15:0] add_ln58_12_fu_1871_p2;
reg   [15:0] add_ln58_12_reg_2445;
wire   [15:0] add_ln58_15_fu_1877_p2;
reg   [15:0] add_ln58_15_reg_2450;
wire   [15:0] add_ln58_18_fu_1882_p2;
reg   [15:0] add_ln58_18_reg_2455;
wire   [12:0] add_ln58_20_fu_1888_p2;
reg   [12:0] add_ln58_20_reg_2460;
wire   [15:0] add_ln58_24_fu_1894_p2;
reg   [15:0] add_ln58_24_reg_2465;
wire   [10:0] add_ln58_27_fu_1899_p2;
reg   [10:0] add_ln58_27_reg_2470;
wire   [15:0] add_ln58_30_fu_1905_p2;
reg   [15:0] add_ln58_30_reg_2475;
wire   [15:0] add_ln58_33_fu_1910_p2;
reg   [15:0] add_ln58_33_reg_2480;
wire   [15:0] add_ln58_36_fu_1916_p2;
reg   [15:0] add_ln58_36_reg_2485;
wire   [15:0] add_ln58_39_fu_1921_p2;
reg   [15:0] add_ln58_39_reg_2490;
wire   [15:0] add_ln58_42_fu_1927_p2;
reg   [15:0] add_ln58_42_reg_2495;
reg   [13:0] trunc_ln42_s_reg_2500;
reg   [12:0] trunc_ln42_38_reg_2505;
reg   [13:0] trunc_ln42_42_reg_2510;
wire   [15:0] add_ln58_4_fu_1984_p2;
reg   [15:0] add_ln58_4_reg_2515;
wire   [15:0] add_ln58_10_fu_1995_p2;
reg   [15:0] add_ln58_10_reg_2520;
wire   [15:0] add_ln58_16_fu_2006_p2;
reg   [15:0] add_ln58_16_reg_2525;
wire   [15:0] add_ln58_28_fu_2020_p2;
reg   [15:0] add_ln58_28_reg_2530;
wire   [15:0] add_ln58_34_fu_2032_p2;
reg   [15:0] add_ln58_34_reg_2535;
wire   [15:0] add_ln58_40_fu_2043_p2;
reg   [15:0] add_ln58_40_reg_2540;
wire   [15:0] add_ln58_45_fu_2048_p2;
reg   [15:0] add_ln58_45_reg_2545;
wire   [15:0] add_ln58_5_fu_2072_p2;
reg   [15:0] add_ln58_5_reg_2550;
wire   [15:0] add_ln58_11_fu_2082_p2;
reg   [15:0] add_ln58_11_reg_2555;
wire   [15:0] add_ln58_17_fu_2092_p2;
reg   [15:0] add_ln58_17_reg_2560;
wire   [14:0] add_ln58_22_fu_2106_p2;
reg   [14:0] add_ln58_22_reg_2565;
wire   [15:0] add_ln58_29_fu_2117_p2;
reg   [15:0] add_ln58_29_reg_2570;
wire   [15:0] add_ln58_35_fu_2127_p2;
reg   [15:0] add_ln58_35_reg_2575;
wire   [15:0] add_ln58_41_fu_2137_p2;
reg   [15:0] add_ln58_41_reg_2580;
wire   [15:0] add_ln58_46_fu_2148_p2;
reg   [15:0] add_ln58_46_reg_2585;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage2_subdone;
reg   [15:0] ap_port_reg_data_0_val;
reg   [15:0] ap_port_reg_data_2_val;
reg   [15:0] ap_port_reg_data_4_val;
reg  signed [15:0] grp_fu_214_p0;
reg  signed [10:0] grp_fu_214_p1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage3;
reg  signed [15:0] grp_fu_215_p0;
reg  signed [10:0] grp_fu_215_p1;
reg  signed [15:0] grp_fu_216_p0;
reg  signed [10:0] grp_fu_216_p1;
reg  signed [15:0] grp_fu_217_p0;
reg  signed [11:0] grp_fu_217_p1;
reg  signed [15:0] grp_fu_218_p0;
reg  signed [10:0] grp_fu_218_p1;
reg  signed [15:0] grp_fu_219_p0;
reg  signed [11:0] grp_fu_219_p1;
reg  signed [15:0] grp_fu_220_p0;
reg   [10:0] grp_fu_220_p1;
reg  signed [15:0] grp_fu_221_p0;
reg  signed [11:0] grp_fu_221_p1;
reg  signed [15:0] grp_fu_222_p0;
reg  signed [10:0] grp_fu_222_p1;
reg  signed [15:0] grp_fu_223_p0;
reg  signed [11:0] grp_fu_223_p1;
reg  signed [15:0] grp_fu_224_p0;
reg  signed [9:0] grp_fu_224_p1;
reg  signed [15:0] grp_fu_225_p0;
reg  signed [11:0] grp_fu_225_p1;
wire   [25:0] grp_fu_221_p2;
wire   [25:0] grp_fu_224_p2;
wire   [25:0] grp_fu_217_p2;
wire   [25:0] grp_fu_218_p2;
wire   [25:0] grp_fu_214_p2;
wire   [25:0] grp_fu_219_p2;
wire   [25:0] grp_fu_223_p2;
wire   [25:0] grp_fu_220_p2;
wire   [25:0] grp_fu_225_p2;
wire   [24:0] grp_fu_1521_p1;
wire   [25:0] grp_fu_216_p2;
wire   [25:0] grp_fu_222_p2;
wire   [24:0] grp_fu_1541_p1;
wire   [25:0] grp_fu_215_p2;
wire  signed [15:0] sext_ln70_4_fu_1603_p0;
wire  signed [15:0] sext_ln70_8_fu_1612_p0;
wire  signed [15:0] sext_ln70_15_fu_1617_p0;
wire  signed [15:0] sext_ln70_17_fu_1622_p0;
wire  signed [15:0] sext_ln70_5_fu_1635_p0;
wire  signed [15:0] sext_ln70_6_fu_1640_p0;
wire   [21:0] trunc_ln42_26_fu_1655_p1;
wire   [21:0] trunc_ln42_13_fu_1675_p1;
wire  signed [15:0] sext_ln70_11_fu_1699_p0;
wire  signed [15:0] sext_ln70_13_fu_1706_p0;
wire  signed [15:0] sext_ln70_14_fu_1711_p0;
wire  signed [15:0] sext_ln70_fu_1717_p0;
wire  signed [15:0] sext_ln70_1_fu_1722_p0;
wire  signed [15:0] sext_ln70_2_fu_1727_p0;
wire   [24:0] trunc_ln42_29_fu_1747_p1;
wire   [23:0] trunc_ln42_31_fu_1764_p1;
wire  signed [16:0] sext_ln70_12_fu_1761_p1;
wire   [16:0] sub_ln73_fu_1774_p2;
wire   [6:0] trunc_ln42_34_fu_1780_p4;
wire   [23:0] trunc_ln42_37_fu_1794_p1;
wire   [18:0] shl_ln_fu_1808_p3;
wire   [16:0] shl_ln73_1_fu_1819_p3;
wire  signed [19:0] sext_ln73_1_fu_1826_p1;
wire  signed [19:0] sext_ln73_fu_1815_p1;
wire   [19:0] sub_ln73_1_fu_1830_p2;
wire   [9:0] trunc_ln42_43_fu_1836_p4;
wire  signed [12:0] sext_ln73_2_fu_1744_p1;
wire  signed [12:0] sext_ln73_3_fu_1790_p1;
wire  signed [10:0] sext_ln73_5_fu_1846_p1;
wire  signed [15:0] sext_ln42_3_fu_1740_p1;
wire  signed [15:0] sext_ln42_2_fu_1737_p1;
wire   [23:0] trunc_ln42_s_fu_1932_p1;
wire   [22:0] trunc_ln42_38_fu_1955_p1;
wire   [23:0] trunc_ln42_42_fu_1965_p1;
wire  signed [15:0] sext_ln42_5_fu_1945_p1;
wire   [15:0] add_ln58_2_fu_1979_p2;
wire   [15:0] add_ln58_8_fu_1989_p2;
wire  signed [15:0] sext_ln42_6_fu_1948_p1;
wire   [15:0] add_ln58_14_fu_2000_p2;
wire  signed [15:0] sext_ln58_2_fu_2017_p1;
wire   [15:0] add_ln58_26_fu_2011_p2;
wire   [15:0] add_ln58_32_fu_2026_p2;
wire  signed [15:0] sext_ln42_4_fu_1942_p1;
wire  signed [15:0] sext_ln42_7_fu_1952_p1;
wire   [15:0] add_ln58_38_fu_2037_p2;
wire  signed [15:0] sext_ln42_9_fu_1975_p1;
wire   [15:0] add_ln58_1_fu_2067_p2;
wire  signed [15:0] sext_ln42_fu_2054_p1;
wire   [15:0] add_ln58_7_fu_2077_p2;
wire   [15:0] add_ln58_13_fu_2087_p2;
wire  signed [14:0] sext_ln73_4_fu_2064_p1;
wire   [14:0] add_ln58_21_fu_2100_p2;
wire  signed [14:0] sext_ln58_fu_2097_p1;
wire  signed [15:0] sext_ln42_1_fu_2057_p1;
wire   [15:0] add_ln58_25_fu_2112_p2;
wire   [15:0] add_ln58_31_fu_2122_p2;
wire   [15:0] add_ln58_37_fu_2132_p2;
wire  signed [15:0] sext_ln42_8_fu_2061_p1;
wire   [15:0] add_ln58_44_fu_2142_p2;
wire  signed [15:0] sext_ln58_1_fu_2158_p1;
wire   [15:0] add_ln58_19_fu_2153_p2;
wire   [15:0] add_ln58_43_fu_2167_p2;
wire   [15:0] add_ln58_23_fu_2161_p2;
wire   [15:0] add_ln58_47_fu_2172_p2;
reg    grp_fu_214_ce;
reg    grp_fu_215_ce;
reg    grp_fu_216_ce;
reg    grp_fu_217_ce;
reg    grp_fu_218_ce;
reg    grp_fu_219_ce;
reg    grp_fu_220_ce;
reg    grp_fu_221_ce;
reg    grp_fu_222_ce;
reg    grp_fu_223_ce;
reg    grp_fu_224_ce;
reg    grp_fu_225_ce;
reg   [3:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

myproject_mul_16s_11s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_1_U57(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_214_p0),
    .din1(grp_fu_214_p1),
    .ce(grp_fu_214_ce),
    .dout(grp_fu_214_p2)
);

myproject_mul_16s_11s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_1_U58(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_215_p0),
    .din1(grp_fu_215_p1),
    .ce(grp_fu_215_ce),
    .dout(grp_fu_215_p2)
);

myproject_mul_16s_11s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_1_U59(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_216_p0),
    .din1(grp_fu_216_p1),
    .ce(grp_fu_216_ce),
    .dout(grp_fu_216_p2)
);

myproject_mul_16s_12s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_1_U60(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_217_p0),
    .din1(grp_fu_217_p1),
    .ce(grp_fu_217_ce),
    .dout(grp_fu_217_p2)
);

myproject_mul_16s_11s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_1_U61(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_218_p0),
    .din1(grp_fu_218_p1),
    .ce(grp_fu_218_ce),
    .dout(grp_fu_218_p2)
);

myproject_mul_16s_12s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_1_U62(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_219_p0),
    .din1(grp_fu_219_p1),
    .ce(grp_fu_219_ce),
    .dout(grp_fu_219_p2)
);

myproject_mul_16s_11ns_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_1_U63(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_220_p0),
    .din1(grp_fu_220_p1),
    .ce(grp_fu_220_ce),
    .dout(grp_fu_220_p2)
);

myproject_mul_16s_12s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_1_U64(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_221_p0),
    .din1(grp_fu_221_p1),
    .ce(grp_fu_221_ce),
    .dout(grp_fu_221_p2)
);

myproject_mul_16s_11s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_1_U65(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_222_p0),
    .din1(grp_fu_222_p1),
    .ce(grp_fu_222_ce),
    .dout(grp_fu_222_p2)
);

myproject_mul_16s_12s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_1_U66(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_223_p0),
    .din1(grp_fu_223_p1),
    .ce(grp_fu_223_ce),
    .dout(grp_fu_223_p2)
);

myproject_mul_16s_10s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_1_U67(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_224_p0),
    .din1(grp_fu_224_p1),
    .ce(grp_fu_224_ce),
    .dout(grp_fu_224_p2)
);

myproject_mul_16s_12s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_1_U68(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_225_p0),
    .din1(grp_fu_225_p1),
    .ce(grp_fu_225_ce),
    .dout(grp_fu_225_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln58_10_reg_2520 <= add_ln58_10_fu_1995_p2;
        add_ln58_16_reg_2525 <= add_ln58_16_fu_2006_p2;
        add_ln58_28_reg_2530 <= add_ln58_28_fu_2020_p2;
        add_ln58_34_reg_2535 <= add_ln58_34_fu_2032_p2;
        add_ln58_40_reg_2540 <= add_ln58_40_fu_2043_p2;
        add_ln58_45_reg_2545 <= add_ln58_45_fu_2048_p2;
        add_ln58_4_reg_2515 <= add_ln58_4_fu_1984_p2;
        data_1_val_read_reg_2232 <= data_1_val;
        data_3_val_read_reg_2226 <= data_3_val;
        data_5_val_read_reg_2219 <= data_5_val;
        sext_ln70_4_reg_2237 <= sext_ln70_4_fu_1603_p1;
        trunc_ln42_38_reg_2505 <= {{trunc_ln42_38_fu_1955_p1[22:10]}};
        trunc_ln42_42_reg_2510 <= {{trunc_ln42_42_fu_1965_p1[23:10]}};
        trunc_ln42_s_reg_2500 <= {{trunc_ln42_s_fu_1932_p1[23:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        add_ln58_11_reg_2555 <= add_ln58_11_fu_2082_p2;
        add_ln58_17_reg_2560 <= add_ln58_17_fu_2092_p2;
        add_ln58_22_reg_2565 <= add_ln58_22_fu_2106_p2;
        add_ln58_29_reg_2570 <= add_ln58_29_fu_2117_p2;
        add_ln58_35_reg_2575 <= add_ln58_35_fu_2127_p2;
        add_ln58_41_reg_2580 <= add_ln58_41_fu_2137_p2;
        add_ln58_46_reg_2585 <= add_ln58_46_fu_2148_p2;
        add_ln58_5_reg_2550 <= add_ln58_5_fu_2072_p2;
        sext_ln70_9_reg_2286 <= sext_ln70_9_fu_1651_p1;
        trunc_ln42_26_reg_2296 <= {{trunc_ln42_26_fu_1655_p1[21:10]}};
        trunc_ln42_41_reg_2306 <= {{grp_fu_215_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln58_12_reg_2445 <= add_ln58_12_fu_1871_p2;
        add_ln58_15_reg_2450 <= add_ln58_15_fu_1877_p2;
        add_ln58_18_reg_2455 <= add_ln58_18_fu_1882_p2;
        add_ln58_20_reg_2460 <= add_ln58_20_fu_1888_p2;
        add_ln58_24_reg_2465 <= add_ln58_24_fu_1894_p2;
        add_ln58_27_reg_2470 <= add_ln58_27_fu_1899_p2;
        add_ln58_30_reg_2475 <= add_ln58_30_fu_1905_p2;
        add_ln58_33_reg_2480 <= add_ln58_33_fu_1910_p2;
        add_ln58_36_reg_2485 <= add_ln58_36_fu_1916_p2;
        add_ln58_39_reg_2490 <= add_ln58_39_fu_1921_p2;
        add_ln58_3_reg_2430 <= add_ln58_3_fu_1855_p2;
        add_ln58_42_reg_2495 <= add_ln58_42_fu_1927_p2;
        add_ln58_6_reg_2435 <= add_ln58_6_fu_1860_p2;
        add_ln58_9_reg_2440 <= add_ln58_9_fu_1865_p2;
        add_ln58_reg_2425 <= add_ln58_fu_1850_p2;
        trunc_ln42_29_reg_2400 <= {{trunc_ln42_29_fu_1747_p1[24:10]}};
        trunc_ln42_31_reg_2410 <= {{trunc_ln42_31_fu_1764_p1[23:10]}};
        trunc_ln42_37_reg_2415 <= {{trunc_ln42_37_fu_1794_p1[23:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_port_reg_data_0_val <= data_0_val;
        ap_port_reg_data_2_val <= data_2_val;
        ap_port_reg_data_4_val <= data_4_val;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        data_4_val_read_reg_2311 <= ap_port_reg_data_4_val;
        trunc_ln42_13_reg_2322 <= {{trunc_ln42_13_fu_1675_p1[21:10]}};
        trunc_ln42_23_reg_2357 <= {{grp_fu_216_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce)))) begin
        reg_1551 <= {{grp_fu_221_p2[25:10]}};
        reg_1563 <= {{grp_fu_218_p2[25:10]}};
        reg_1571 <= {{grp_fu_223_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce)))) begin
        reg_1555 <= {{grp_fu_224_p2[25:10]}};
        reg_1559 <= {{grp_fu_217_p2[25:10]}};
        reg_1575 <= {{grp_fu_220_p2[25:10]}};
        reg_1579 <= {{grp_fu_225_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce)))) begin
        reg_1567 <= {{grp_fu_214_p2[25:10]}};
        reg_1583 <= {{grp_fu_1521_p1[24:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_1587 <= {{grp_fu_217_p2[25:10]}};
        reg_1595 <= {{grp_fu_219_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_1591 <= {{grp_fu_222_p2[25:10]}};
        reg_1599 <= {{grp_fu_1541_p1[24:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        trunc_ln42_12_reg_2317 <= {{grp_fu_221_p2[25:10]}};
        trunc_ln42_15_reg_2327 <= {{grp_fu_218_p2[25:10]}};
        trunc_ln42_16_reg_2332 <= {{grp_fu_214_p2[25:10]}};
        trunc_ln42_19_reg_2337 <= {{grp_fu_223_p2[25:10]}};
        trunc_ln42_21_reg_2342 <= {{grp_fu_220_p2[25:10]}};
        trunc_ln42_22_reg_2347 <= {{grp_fu_225_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        trunc_ln42_39_reg_2301 <= {{grp_fu_219_p2[25:10]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_214_ce = 1'b1;
    end else begin
        grp_fu_214_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_214_p0 = sext_ln70_2_fu_1727_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_214_p0 = sext_ln70_7_fu_1685_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_214_p0 = sext_ln70_6_fu_1640_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_214_p0 = sext_ln70_4_fu_1603_p1;
        end else begin
            grp_fu_214_p0 = 'bx;
        end
    end else begin
        grp_fu_214_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_214_p1 = 26'd67108194;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_214_p1 = 25'd183;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_214_p1 = 26'd302;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_214_p1 = 26'd332;
        end else begin
            grp_fu_214_p1 = 'bx;
        end
    end else begin
        grp_fu_214_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_215_ce = 1'b1;
    end else begin
        grp_fu_215_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_215_p0 = sext_ln70_10_fu_1757_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_215_p0 = sext_ln70_13_fu_1706_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_215_p0 = sext_ln70_5_fu_1635_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_215_p0 = sext_ln70_17_fu_1622_p1;
        end else begin
            grp_fu_215_p0 = 'bx;
        end
    end else begin
        grp_fu_215_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_215_p1 = 23'd39;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_215_p1 = 25'd33554282;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_215_p1 = 25'd173;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_215_p1 = 26'd428;
        end else begin
            grp_fu_215_p1 = 'bx;
        end
    end else begin
        grp_fu_215_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_216_ce = 1'b1;
    end else begin
        grp_fu_216_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_216_p0 = sext_ln70_fu_1717_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_216_p0 = sext_ln70_14_fu_1711_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_216_p0 = sext_ln70_9_fu_1651_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_216_p0 = sext_ln70_15_fu_1617_p1;
        end else begin
            grp_fu_216_p0 = 'bx;
        end
    end else begin
        grp_fu_216_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_216_p1 = 25'd253;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_216_p1 = 24'd103;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_216_p1 = 26'd67108303;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_216_p1 = 25'd146;
        end else begin
            grp_fu_216_p1 = 'bx;
        end
    end else begin
        grp_fu_216_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_217_ce = 1'b1;
    end else begin
        grp_fu_217_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_217_p0 = sext_ln70_2_fu_1727_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_217_p0 = sext_ln70_9_reg_2286;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_217_p0 = sext_ln70_4_reg_2237;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_217_p0 = sext_ln70_4_fu_1603_p1;
        end else begin
            grp_fu_217_p0 = 'bx;
        end
    end else begin
        grp_fu_217_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_217_p1 = 26'd347;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_217_p1 = 26'd67108388;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_217_p1 = 26'd985;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_217_p1 = 26'd67108211;
        end else begin
            grp_fu_217_p1 = 'bx;
        end
    end else begin
        grp_fu_217_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_218_ce = 1'b1;
    end else begin
        grp_fu_218_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_218_p0 = sext_ln70_2_fu_1727_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_218_p0 = sext_ln70_9_reg_2286;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_218_p0 = sext_ln70_6_fu_1640_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_218_p0 = sext_ln70_4_fu_1603_p1;
        end else begin
            grp_fu_218_p0 = 'bx;
        end
    end else begin
        grp_fu_218_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_218_p1 = 26'd67108427;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_218_p1 = 26'd295;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_218_p1 = 26'd499;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_218_p1 = 26'd67108464;
        end else begin
            grp_fu_218_p1 = 'bx;
        end
    end else begin
        grp_fu_218_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_219_ce = 1'b1;
    end else begin
        grp_fu_219_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_219_p0 = sext_ln70_2_fu_1727_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_219_p0 = sext_ln70_14_fu_1711_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_219_p0 = sext_ln70_6_fu_1640_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_219_p0 = sext_ln70_17_fu_1622_p1;
        end else begin
            grp_fu_219_p0 = 'bx;
        end
    end else begin
        grp_fu_219_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_219_p1 = 26'd67108536;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_219_p1 = 24'd16777122;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_219_p1 = 26'd297;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_219_p1 = 26'd518;
        end else begin
            grp_fu_219_p1 = 'bx;
        end
    end else begin
        grp_fu_219_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_220_ce = 1'b1;
    end else begin
        grp_fu_220_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_220_p0 = sext_ln70_11_fu_1699_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_220_p0 = sext_ln70_6_fu_1640_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_220_p0 = sext_ln70_17_fu_1622_p1;
        end else begin
            grp_fu_220_p0 = 'bx;
        end
    end else begin
        grp_fu_220_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_220_p1 = 26'd503;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_220_p1 = 26'd639;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_220_p1 = 26'd326;
        end else begin
            grp_fu_220_p1 = 'bx;
        end
    end else begin
        grp_fu_220_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_221_ce = 1'b1;
    end else begin
        grp_fu_221_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_221_p0 = sext_ln70_2_fu_1727_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_221_p0 = sext_ln70_9_reg_2286;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_221_p0 = sext_ln70_4_reg_2237;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_221_p0 = sext_ln70_4_fu_1603_p1;
        end else begin
            grp_fu_221_p0 = 'bx;
        end
    end else begin
        grp_fu_221_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_221_p1 = 26'd296;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_221_p1 = 26'd546;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_221_p1 = 26'd914;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_221_p1 = 26'd67108545;
        end else begin
            grp_fu_221_p1 = 'bx;
        end
    end else begin
        grp_fu_221_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_222_ce = 1'b1;
    end else begin
        grp_fu_222_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_222_p0 = sext_ln70_9_reg_2286;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_222_p0 = sext_ln70_6_fu_1640_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_222_p0 = sext_ln70_8_fu_1612_p1;
        end else begin
            grp_fu_222_p0 = 'bx;
        end
    end else begin
        grp_fu_222_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_222_p1 = 26'd67108371;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_222_p1 = 26'd463;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_222_p1 = 22'd29;
        end else begin
            grp_fu_222_p1 = 'bx;
        end
    end else begin
        grp_fu_222_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_223_ce = 1'b1;
    end else begin
        grp_fu_223_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_223_p0 = sext_ln70_2_fu_1727_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_223_p0 = sext_ln70_11_fu_1699_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_223_p0 = sext_ln70_6_fu_1640_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_223_p0 = sext_ln70_17_fu_1622_p1;
        end else begin
            grp_fu_223_p0 = 'bx;
        end
    end else begin
        grp_fu_223_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_223_p1 = 26'd604;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_223_p1 = 26'd611;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_223_p1 = 26'd67108370;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_223_p1 = 26'd67108401;
        end else begin
            grp_fu_223_p1 = 'bx;
        end
    end else begin
        grp_fu_223_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_224_ce = 1'b1;
    end else begin
        grp_fu_224_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_224_p0 = sext_ln70_16_fu_1804_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_224_p0 = sext_ln70_9_reg_2286;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_224_p0 = sext_ln70_3_fu_1631_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_224_p0 = sext_ln70_4_fu_1603_p1;
        end else begin
            grp_fu_224_p0 = 'bx;
        end
    end else begin
        grp_fu_224_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_224_p1 = 24'd16777112;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_224_p1 = 26'd67108527;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_224_p1 = 22'd4194282;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_224_p1 = 26'd67108424;
        end else begin
            grp_fu_224_p1 = 'bx;
        end
    end else begin
        grp_fu_224_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_225_ce = 1'b1;
    end else begin
        grp_fu_225_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_225_p0 = sext_ln70_1_fu_1722_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_225_p0 = sext_ln70_11_fu_1699_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_225_p0 = sext_ln70_6_fu_1640_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_225_p0 = sext_ln70_17_fu_1622_p1;
        end else begin
            grp_fu_225_p0 = 'bx;
        end
    end else begin
        grp_fu_225_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_225_p1 = 24'd16777093;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_225_p1 = 26'd596;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_225_p1 = 26'd67108273;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_225_p1 = 26'd67108262;
        end else begin
            grp_fu_225_p1 = 'bx;
        end
    end else begin
        grp_fu_225_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if (((ap_reset_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_10_fu_1995_p2 = (add_ln58_9_reg_2440 + add_ln58_8_fu_1989_p2);

assign add_ln58_11_fu_2082_p2 = (add_ln58_10_reg_2520 + add_ln58_7_fu_2077_p2);

assign add_ln58_12_fu_1871_p2 = (reg_1559 + reg_1591);

assign add_ln58_13_fu_2087_p2 = (add_ln58_12_reg_2445 + reg_1551);

assign add_ln58_14_fu_2000_p2 = ($signed(reg_1555) + $signed(sext_ln42_6_fu_1948_p1));

assign add_ln58_15_fu_1877_p2 = (trunc_ln42_41_reg_2306 + 16'd44);

assign add_ln58_16_fu_2006_p2 = (add_ln58_15_reg_2450 + add_ln58_14_fu_2000_p2);

assign add_ln58_17_fu_2092_p2 = (add_ln58_16_reg_2525 + add_ln58_13_fu_2087_p2);

assign add_ln58_18_fu_1882_p2 = (reg_1563 + reg_1595);

assign add_ln58_19_fu_2153_p2 = (add_ln58_18_reg_2455 + reg_1595);

assign add_ln58_1_fu_2067_p2 = (add_ln58_reg_2425 + reg_1563);

assign add_ln58_20_fu_1888_p2 = ($signed(sext_ln73_2_fu_1744_p1) + $signed(sext_ln73_3_fu_1790_p1));

assign add_ln58_21_fu_2100_p2 = ($signed(sext_ln73_4_fu_2064_p1) + $signed(15'd16));

assign add_ln58_22_fu_2106_p2 = ($signed(add_ln58_21_fu_2100_p2) + $signed(sext_ln58_fu_2097_p1));

assign add_ln58_23_fu_2161_p2 = ($signed(sext_ln58_1_fu_2158_p1) + $signed(add_ln58_19_fu_2153_p2));

assign add_ln58_24_fu_1894_p2 = (reg_1567 + trunc_ln42_19_reg_2337);

assign add_ln58_25_fu_2112_p2 = ($signed(add_ln58_24_reg_2465) + $signed(sext_ln42_1_fu_2057_p1));

assign add_ln58_26_fu_2011_p2 = (reg_1559 + reg_1575);

assign add_ln58_27_fu_1899_p2 = ($signed(sext_ln73_5_fu_1846_p1) + $signed(11'd315));

assign add_ln58_28_fu_2020_p2 = ($signed(sext_ln58_2_fu_2017_p1) + $signed(add_ln58_26_fu_2011_p2));

assign add_ln58_29_fu_2117_p2 = (add_ln58_28_reg_2530 + add_ln58_25_fu_2112_p2);

assign add_ln58_2_fu_1979_p2 = ($signed(trunc_ln42_23_reg_2357) + $signed(sext_ln42_5_fu_1945_p1));

assign add_ln58_30_fu_1905_p2 = ($signed(trunc_ln42_12_reg_2317) + $signed(sext_ln42_3_fu_1740_p1));

assign add_ln58_31_fu_2122_p2 = (add_ln58_30_reg_2475 + reg_1567);

assign add_ln58_32_fu_2026_p2 = (reg_1563 + reg_1579);

assign add_ln58_33_fu_1910_p2 = ($signed(reg_1575) + $signed(16'd64400));

assign add_ln58_34_fu_2032_p2 = (add_ln58_33_reg_2480 + add_ln58_32_fu_2026_p2);

assign add_ln58_35_fu_2127_p2 = (add_ln58_34_reg_2535 + add_ln58_31_fu_2122_p2);

assign add_ln58_36_fu_1916_p2 = ($signed(sext_ln42_2_fu_1737_p1) + $signed(trunc_ln42_21_reg_2342));

assign add_ln58_37_fu_2132_p2 = (add_ln58_36_reg_2485 + reg_1571);

assign add_ln58_38_fu_2037_p2 = ($signed(sext_ln42_4_fu_1942_p1) + $signed(sext_ln42_7_fu_1952_p1));

assign add_ln58_39_fu_1921_p2 = ($signed(reg_1579) + $signed(16'd64737));

assign add_ln58_3_fu_1855_p2 = ($signed(trunc_ln42_39_reg_2301) + $signed(16'd65195));

assign add_ln58_40_fu_2043_p2 = (add_ln58_39_reg_2490 + add_ln58_38_fu_2037_p2);

assign add_ln58_41_fu_2137_p2 = (add_ln58_40_reg_2540 + add_ln58_37_fu_2132_p2);

assign add_ln58_42_fu_1927_p2 = (reg_1587 + trunc_ln42_22_reg_2347);

assign add_ln58_43_fu_2167_p2 = (add_ln58_42_reg_2495 + reg_1587);

assign add_ln58_44_fu_2142_p2 = ($signed(reg_1591) + $signed(sext_ln42_8_fu_2061_p1));

assign add_ln58_45_fu_2048_p2 = ($signed(sext_ln42_9_fu_1975_p1) + $signed(16'd65320));

assign add_ln58_46_fu_2148_p2 = (add_ln58_45_reg_2545 + add_ln58_44_fu_2142_p2);

assign add_ln58_47_fu_2172_p2 = (add_ln58_46_reg_2585 + add_ln58_43_fu_2167_p2);

assign add_ln58_4_fu_1984_p2 = (add_ln58_3_reg_2430 + add_ln58_2_fu_1979_p2);

assign add_ln58_5_fu_2072_p2 = (add_ln58_4_reg_2515 + add_ln58_1_fu_2067_p2);

assign add_ln58_6_fu_1860_p2 = (reg_1555 + trunc_ln42_16_reg_2332);

assign add_ln58_7_fu_2077_p2 = ($signed(add_ln58_6_reg_2435) + $signed(sext_ln42_fu_2054_p1));

assign add_ln58_8_fu_1989_p2 = (reg_1551 + reg_1571);

assign add_ln58_9_fu_1865_p2 = (reg_1571 + 16'd40);

assign add_ln58_fu_1850_p2 = (reg_1551 + trunc_ln42_15_reg_2327);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return_0 = add_ln58_5_reg_2550;

assign ap_return_1 = add_ln58_11_reg_2555;

assign ap_return_2 = add_ln58_17_reg_2560;

assign ap_return_3 = add_ln58_23_fu_2161_p2;

assign ap_return_4 = add_ln58_29_reg_2570;

assign ap_return_5 = add_ln58_35_reg_2575;

assign ap_return_6 = add_ln58_41_reg_2580;

assign ap_return_7 = add_ln58_47_fu_2172_p2;

assign grp_fu_1521_p1 = grp_fu_216_p2;

assign grp_fu_1541_p1 = grp_fu_215_p2;

assign sext_ln42_1_fu_2057_p1 = $signed(reg_1583);

assign sext_ln42_2_fu_1737_p1 = $signed(trunc_ln42_13_reg_2322);

assign sext_ln42_3_fu_1740_p1 = $signed(reg_1599);

assign sext_ln42_4_fu_1942_p1 = $signed(trunc_ln42_29_reg_2400);

assign sext_ln42_5_fu_1945_p1 = $signed(trunc_ln42_31_reg_2410);

assign sext_ln42_6_fu_1948_p1 = $signed(reg_1599);

assign sext_ln42_7_fu_1952_p1 = $signed(trunc_ln42_37_reg_2415);

assign sext_ln42_8_fu_2061_p1 = $signed(trunc_ln42_38_reg_2505);

assign sext_ln42_9_fu_1975_p1 = $signed(reg_1583);

assign sext_ln42_fu_2054_p1 = $signed(trunc_ln42_s_reg_2500);

assign sext_ln58_1_fu_2158_p1 = $signed(add_ln58_22_reg_2565);

assign sext_ln58_2_fu_2017_p1 = $signed(add_ln58_27_reg_2470);

assign sext_ln58_fu_2097_p1 = $signed(add_ln58_20_reg_2460);

assign sext_ln70_10_fu_1757_p1 = data_4_val_read_reg_2311;

assign sext_ln70_11_fu_1699_p0 = ap_port_reg_data_4_val;

assign sext_ln70_11_fu_1699_p1 = sext_ln70_11_fu_1699_p0;

assign sext_ln70_12_fu_1761_p1 = data_4_val_read_reg_2311;

assign sext_ln70_13_fu_1706_p0 = ap_port_reg_data_4_val;

assign sext_ln70_13_fu_1706_p1 = sext_ln70_13_fu_1706_p0;

assign sext_ln70_14_fu_1711_p0 = ap_port_reg_data_4_val;

assign sext_ln70_14_fu_1711_p1 = sext_ln70_14_fu_1711_p0;

assign sext_ln70_15_fu_1617_p0 = data_5_val;

assign sext_ln70_15_fu_1617_p1 = sext_ln70_15_fu_1617_p0;

assign sext_ln70_16_fu_1804_p1 = data_5_val_read_reg_2219;

assign sext_ln70_17_fu_1622_p0 = data_5_val;

assign sext_ln70_17_fu_1622_p1 = sext_ln70_17_fu_1622_p0;

assign sext_ln70_1_fu_1722_p0 = ap_port_reg_data_0_val;

assign sext_ln70_1_fu_1722_p1 = sext_ln70_1_fu_1722_p0;

assign sext_ln70_2_fu_1727_p0 = ap_port_reg_data_0_val;

assign sext_ln70_2_fu_1727_p1 = sext_ln70_2_fu_1727_p0;

assign sext_ln70_3_fu_1631_p1 = data_1_val_read_reg_2232;

assign sext_ln70_4_fu_1603_p0 = data_1_val;

assign sext_ln70_4_fu_1603_p1 = sext_ln70_4_fu_1603_p0;

assign sext_ln70_5_fu_1635_p0 = ap_port_reg_data_2_val;

assign sext_ln70_5_fu_1635_p1 = sext_ln70_5_fu_1635_p0;

assign sext_ln70_6_fu_1640_p0 = ap_port_reg_data_2_val;

assign sext_ln70_6_fu_1640_p1 = sext_ln70_6_fu_1640_p0;

assign sext_ln70_7_fu_1685_p1 = data_3_val_read_reg_2226;

assign sext_ln70_8_fu_1612_p0 = data_3_val;

assign sext_ln70_8_fu_1612_p1 = sext_ln70_8_fu_1612_p0;

assign sext_ln70_9_fu_1651_p1 = data_3_val_read_reg_2226;

assign sext_ln70_fu_1717_p0 = ap_port_reg_data_0_val;

assign sext_ln70_fu_1717_p1 = sext_ln70_fu_1717_p0;

assign sext_ln73_1_fu_1826_p1 = $signed(shl_ln73_1_fu_1819_p3);

assign sext_ln73_2_fu_1744_p1 = $signed(trunc_ln42_26_reg_2296);

assign sext_ln73_3_fu_1790_p1 = $signed(trunc_ln42_34_fu_1780_p4);

assign sext_ln73_4_fu_2064_p1 = $signed(trunc_ln42_42_reg_2510);

assign sext_ln73_5_fu_1846_p1 = $signed(trunc_ln42_43_fu_1836_p4);

assign sext_ln73_fu_1815_p1 = $signed(shl_ln_fu_1808_p3);

assign shl_ln73_1_fu_1819_p3 = {{data_5_val_read_reg_2219}, {1'd0}};

assign shl_ln_fu_1808_p3 = {{data_5_val_read_reg_2219}, {3'd0}};

assign sub_ln73_1_fu_1830_p2 = ($signed(sext_ln73_1_fu_1826_p1) - $signed(sext_ln73_fu_1815_p1));

assign sub_ln73_fu_1774_p2 = ($signed(17'd0) - $signed(sext_ln70_12_fu_1761_p1));

assign trunc_ln42_13_fu_1675_p1 = grp_fu_224_p2;

assign trunc_ln42_26_fu_1655_p1 = grp_fu_222_p2;

assign trunc_ln42_29_fu_1747_p1 = grp_fu_214_p2;

assign trunc_ln42_31_fu_1764_p1 = grp_fu_219_p2;

assign trunc_ln42_34_fu_1780_p4 = {{sub_ln73_fu_1774_p2[16:10]}};

assign trunc_ln42_37_fu_1794_p1 = grp_fu_216_p2;

assign trunc_ln42_38_fu_1955_p1 = grp_fu_215_p2;

assign trunc_ln42_42_fu_1965_p1 = grp_fu_224_p2;

assign trunc_ln42_43_fu_1836_p4 = {{sub_ln73_1_fu_1830_p2[19:10]}};

assign trunc_ln42_s_fu_1932_p1 = grp_fu_225_p2;

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s
