-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv26_1B7 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000110110111";
    constant ap_const_lv25_1FFFF6C : STD_LOGIC_VECTOR (24 downto 0) := "1111111111111111101101100";
    constant ap_const_lv25_A5 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000010100101";
    constant ap_const_lv25_D0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000011010000";
    constant ap_const_lv26_21D : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000011101";
    constant ap_const_lv26_3CE : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001111001110";
    constant ap_const_lv26_2F6 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001011110110";
    constant ap_const_lv25_1FFFF4D : STD_LOGIC_VECTOR (24 downto 0) := "1111111111111111101001101";
    constant ap_const_lv26_4AA : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010010101010";
    constant ap_const_lv26_170 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000101110000";
    constant ap_const_lv26_259 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001001011001";
    constant ap_const_lv25_1FFFF29 : STD_LOGIC_VECTOR (24 downto 0) := "1111111111111111100101001";
    constant ap_const_lv26_3FFFE33 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111000110011";
    constant ap_const_lv25_1FFFF33 : STD_LOGIC_VECTOR (24 downto 0) := "1111111111111111100110011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv16_4A : STD_LOGIC_VECTOR (15 downto 0) := "0000000001001010";
    constant ap_const_lv16_DB : STD_LOGIC_VECTOR (15 downto 0) := "0000000011011011";
    constant ap_const_lv16_1B : STD_LOGIC_VECTOR (15 downto 0) := "0000000000011011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal reg_406 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal reg_410 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal reg_414 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_418 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_21_fu_422_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln42_66_reg_837 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln70_25_fu_468_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal data_4_val_read_reg_849 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_22_fu_475_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_23_fu_480_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln42_67_reg_866 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln42_23_fu_531_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln42_70_reg_877 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln70_24_fu_577_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln42_78_reg_887 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_fu_592_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_fu_597_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln42_69_reg_903 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_25_fu_620_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln42_73_reg_913 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_74_reg_918 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln58_fu_672_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_reg_923 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_63_fu_678_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_63_reg_928 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_69_fu_684_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_69_reg_933 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_s_reg_938 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_75_reg_943 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_64_fu_736_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_64_reg_948 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_66_fu_741_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_66_reg_953 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_70_fu_753_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_70_reg_958 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_72_fu_758_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_72_reg_963 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_75_fu_763_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_75_reg_968 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_65_fu_780_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_65_reg_973 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_71_fu_790_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_71_reg_978 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_76_fu_800_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_76_reg_983 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_port_reg_data_0_val : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_data_2_val : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_data_3_val : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_data_4_val : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_144_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_144_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal grp_fu_145_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_145_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal grp_fu_146_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_146_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_147_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_147_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_148_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_148_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_366_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_145_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_376_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_148_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal grp_fu_147_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_146_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_21_fu_422_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln_fu_428_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln_fu_428_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln73_4_fu_440_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln73_4_fu_440_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln73_fu_436_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln73_5_fu_448_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln73_fu_452_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln70_22_fu_475_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_23_fu_480_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln73_5_fu_485_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln73_5_fu_485_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln73_6_fu_493_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln73_6_fu_503_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln73_6_fu_503_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln73_fu_497_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln73_7_fu_511_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sub_ln73_4_fu_515_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln42_23_fu_531_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln73_7_fu_537_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln73_7_fu_537_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln73_8_fu_549_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln73_8_fu_549_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln73_8_fu_545_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln73_9_fu_557_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sub_ln73_5_fu_561_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln70_24_fu_577_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_144_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln42_fu_592_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_fu_597_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_73_fu_624_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal shl_ln73_9_fu_634_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal shl_ln73_s_fu_645_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln73_10_fu_641_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln73_11_fu_652_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln73_1_fu_656_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln42_18_fu_603_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_21_fu_607_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_s_fu_690_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln42_24_fu_711_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_26_fu_714_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_62_fu_730_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_19_fu_700_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_22_fu_707_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_27_fu_717_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_68_fu_747_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_20_fu_704_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_16_fu_768_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_61_fu_775_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_17_fu_772_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_67_fu_785_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_74_fu_795_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_73_fu_805_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_77_fu_810_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_144_ce : STD_LOGIC;
    signal grp_fu_145_ce : STD_LOGIC;
    signal grp_fu_146_ce : STD_LOGIC;
    signal grp_fu_147_ce : STD_LOGIC;
    signal grp_fu_148_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_mul_16s_11s_26_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_11ns_26_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_12s_26_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_12ns_26_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_10s_26_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;



begin
    mul_16s_11s_26_2_1_U27 : component myproject_mul_16s_11s_26_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_144_p0,
        din1 => grp_fu_144_p1,
        ce => grp_fu_144_ce,
        dout => grp_fu_144_p2);

    mul_16s_11ns_26_2_1_U28 : component myproject_mul_16s_11ns_26_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_145_p0,
        din1 => grp_fu_145_p1,
        ce => grp_fu_145_ce,
        dout => grp_fu_145_p2);

    mul_16s_12s_26_2_1_U29 : component myproject_mul_16s_12s_26_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_146_p0,
        din1 => grp_fu_146_p1,
        ce => grp_fu_146_ce,
        dout => grp_fu_146_p2);

    mul_16s_12ns_26_2_1_U30 : component myproject_mul_16s_12ns_26_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_147_p0,
        din1 => grp_fu_147_p1,
        ce => grp_fu_147_ce,
        dout => grp_fu_147_p2);

    mul_16s_10s_26_2_1_U31 : component myproject_mul_16s_10s_26_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_148_p0,
        din1 => grp_fu_148_p1,
        ce => grp_fu_148_ce,
        dout => grp_fu_148_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_logic_1 = ap_ce))) then
                add_ln58_63_reg_928 <= add_ln58_63_fu_678_p2;
                add_ln58_69_reg_933 <= add_ln58_69_fu_684_p2;
                add_ln58_reg_923 <= add_ln58_fu_672_p2;
                trunc_ln42_69_reg_903 <= grp_fu_148_p2(25 downto 10);
                trunc_ln42_73_reg_913 <= trunc_ln42_73_fu_624_p1(24 downto 10);
                trunc_ln42_74_reg_918 <= add_ln73_1_fu_656_p2(22 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                add_ln58_64_reg_948 <= add_ln58_64_fu_736_p2;
                add_ln58_66_reg_953 <= add_ln58_66_fu_741_p2;
                add_ln58_70_reg_958 <= add_ln58_70_fu_753_p2;
                add_ln58_72_reg_963 <= add_ln58_72_fu_758_p2;
                add_ln58_75_reg_968 <= add_ln58_75_fu_763_p2;
                trunc_ln42_75_reg_943 <= grp_fu_145_p2(25 downto 10);
                trunc_ln42_s_reg_938 <= trunc_ln42_s_fu_690_p1(24 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln58_65_reg_973 <= add_ln58_65_fu_780_p2;
                add_ln58_71_reg_978 <= add_ln58_71_fu_790_p2;
                add_ln58_76_reg_983 <= add_ln58_76_fu_800_p2;
                trunc_ln42_66_reg_837 <= add_ln73_fu_452_p2(24 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_port_reg_data_0_val <= data_0_val;
                ap_port_reg_data_2_val <= data_2_val;
                ap_port_reg_data_3_val <= data_3_val;
                ap_port_reg_data_4_val <= data_4_val;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_ce))) then
                data_4_val_read_reg_849 <= ap_port_reg_data_4_val;
                trunc_ln42_67_reg_866 <= sub_ln73_4_fu_515_p2(23 downto 10);
                trunc_ln42_70_reg_877 <= sub_ln73_5_fu_561_p2(24 downto 10);
                trunc_ln42_78_reg_887 <= grp_fu_144_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_logic_1 = ap_ce)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_ce)))) then
                reg_406 <= grp_fu_366_p1(24 downto 10);
                reg_418 <= grp_fu_146_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_ce)))) then
                reg_410 <= grp_fu_376_p1(24 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_logic_1 = ap_ce)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_ce)))) then
                reg_414 <= grp_fu_147_p2(25 downto 10);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_block_pp0_stage3_subdone, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_reset_idle_pp0, ap_block_pp0_stage2_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if (((ap_reset_idle_pp0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                elsif (((ap_reset_idle_pp0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln58_61_fu_775_p2 <= std_logic_vector(unsigned(add_ln58_reg_923) + unsigned(sext_ln42_16_fu_768_p1));
    add_ln58_62_fu_730_p2 <= std_logic_vector(signed(sext_ln42_24_fu_711_p1) + signed(sext_ln42_26_fu_714_p1));
    add_ln58_63_fu_678_p2 <= std_logic_vector(unsigned(reg_414) + unsigned(ap_const_lv16_4A));
    add_ln58_64_fu_736_p2 <= std_logic_vector(unsigned(add_ln58_63_reg_928) + unsigned(add_ln58_62_fu_730_p2));
    add_ln58_65_fu_780_p2 <= std_logic_vector(unsigned(add_ln58_64_reg_948) + unsigned(add_ln58_61_fu_775_p2));
    add_ln58_66_fu_741_p2 <= std_logic_vector(signed(sext_ln42_19_fu_700_p1) + signed(sext_ln42_22_fu_707_p1));
    add_ln58_67_fu_785_p2 <= std_logic_vector(unsigned(add_ln58_66_reg_953) + unsigned(sext_ln42_17_fu_772_p1));
    add_ln58_68_fu_747_p2 <= std_logic_vector(unsigned(reg_414) + unsigned(sext_ln42_27_fu_717_p1));
    add_ln58_69_fu_684_p2 <= std_logic_vector(unsigned(reg_418) + unsigned(ap_const_lv16_DB));
    add_ln58_70_fu_753_p2 <= std_logic_vector(unsigned(add_ln58_69_reg_933) + unsigned(add_ln58_68_fu_747_p2));
    add_ln58_71_fu_790_p2 <= std_logic_vector(unsigned(add_ln58_70_reg_958) + unsigned(add_ln58_67_fu_785_p2));
    add_ln58_72_fu_758_p2 <= std_logic_vector(signed(sext_ln42_20_fu_704_p1) + signed(trunc_ln42_69_reg_903));
    add_ln58_73_fu_805_p2 <= std_logic_vector(unsigned(add_ln58_72_reg_963) + unsigned(reg_414));
    add_ln58_74_fu_795_p2 <= std_logic_vector(unsigned(reg_418) + unsigned(trunc_ln42_75_reg_943));
    add_ln58_75_fu_763_p2 <= std_logic_vector(unsigned(trunc_ln42_78_reg_887) + unsigned(ap_const_lv16_1B));
    add_ln58_76_fu_800_p2 <= std_logic_vector(unsigned(add_ln58_75_reg_968) + unsigned(add_ln58_74_fu_795_p2));
    add_ln58_77_fu_810_p2 <= std_logic_vector(unsigned(add_ln58_76_reg_983) + unsigned(add_ln58_73_fu_805_p2));
    add_ln58_fu_672_p2 <= std_logic_vector(signed(sext_ln42_18_fu_603_p1) + signed(sext_ln42_21_fu_607_p1));
    add_ln73_1_fu_656_p2 <= std_logic_vector(signed(sext_ln73_10_fu_641_p1) + signed(sext_ln73_11_fu_652_p1));
    add_ln73_fu_452_p2 <= std_logic_vector(signed(sext_ln73_fu_436_p1) + signed(sext_ln73_5_fu_448_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage1_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage2_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage3_subdone <= (ap_const_logic_0 = ap_ce);
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= add_ln58_65_reg_973;
    ap_return_1 <= add_ln58_71_reg_978;
    ap_return_2 <= add_ln58_77_fu_810_p2;

    grp_fu_144_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_ce) and (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))))) then 
            grp_fu_144_ce <= ap_const_logic_1;
        else 
            grp_fu_144_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_144_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, sext_ln70_25_fu_468_p1, sext_ln70_24_fu_577_p1, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_144_p0 <= sext_ln70_24_fu_577_p1(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_144_p0 <= sext_ln70_25_fu_468_p1(16 - 1 downto 0);
            else 
                grp_fu_144_p0 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_144_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_144_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_144_p1 <= ap_const_lv25_1FFFF6C(11 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_144_p1 <= ap_const_lv26_1B7(11 - 1 downto 0);
            else 
                grp_fu_144_p1 <= "XXXXXXXXXXX";
            end if;
        else 
            grp_fu_144_p1 <= "XXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_145_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage3, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_ce) and (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))))) then 
            grp_fu_145_ce <= ap_const_logic_1;
        else 
            grp_fu_145_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_145_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, sext_ln70_21_fu_422_p1, sext_ln70_23_fu_480_p1, sext_ln42_25_fu_620_p1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_145_p0 <= sext_ln42_25_fu_620_p1(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_145_p0 <= sext_ln70_23_fu_480_p1(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_145_p0 <= sext_ln70_21_fu_422_p1(16 - 1 downto 0);
            else 
                grp_fu_145_p0 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_145_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_145_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_145_p1 <= ap_const_lv26_21D(11 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_145_p1 <= ap_const_lv25_D0(11 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_145_p1 <= ap_const_lv25_A5(11 - 1 downto 0);
            else 
                grp_fu_145_p1 <= "XXXXXXXXXXX";
            end if;
        else 
            grp_fu_145_p1 <= "XXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_146_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage3, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_ce) and (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))))) then 
            grp_fu_146_ce <= ap_const_logic_1;
        else 
            grp_fu_146_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_146_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, sext_ln70_25_fu_468_p1, sext_ln42_23_fu_531_p1, sext_ln70_fu_597_p1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_146_p0 <= sext_ln70_fu_597_p1(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_146_p0 <= sext_ln42_23_fu_531_p1(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_146_p0 <= sext_ln70_25_fu_468_p1(16 - 1 downto 0);
            else 
                grp_fu_146_p0 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_146_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_146_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_146_p1 <= ap_const_lv25_1FFFF4D(12 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_146_p1 <= ap_const_lv26_2F6(12 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_146_p1 <= ap_const_lv26_3CE(12 - 1 downto 0);
            else 
                grp_fu_146_p1 <= "XXXXXXXXXXXX";
            end if;
        else 
            grp_fu_146_p1 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_147_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage3, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_ce) and (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))))) then 
            grp_fu_147_ce <= ap_const_logic_1;
        else 
            grp_fu_147_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_147_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, sext_ln70_25_fu_468_p1, sext_ln42_23_fu_531_p1, sext_ln42_fu_592_p1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_147_p0 <= sext_ln42_fu_592_p1(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_147_p0 <= sext_ln42_23_fu_531_p1(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_147_p0 <= sext_ln70_25_fu_468_p1(16 - 1 downto 0);
            else 
                grp_fu_147_p0 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_147_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_147_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_147_p1 <= ap_const_lv26_259(12 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_147_p1 <= ap_const_lv26_170(12 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_147_p1 <= ap_const_lv26_4AA(12 - 1 downto 0);
            else 
                grp_fu_147_p1 <= "XXXXXXXXXXXX";
            end if;
        else 
            grp_fu_147_p1 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_148_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage3, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_ce) and (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))))) then 
            grp_fu_148_ce <= ap_const_logic_1;
        else 
            grp_fu_148_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_148_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, sext_ln70_21_fu_422_p1, sext_ln70_22_fu_475_p1, sext_ln70_fu_597_p1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_148_p0 <= sext_ln70_fu_597_p1(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_148_p0 <= sext_ln70_22_fu_475_p1(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_148_p0 <= sext_ln70_21_fu_422_p1(16 - 1 downto 0);
            else 
                grp_fu_148_p0 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_148_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_148_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_148_p1 <= ap_const_lv25_1FFFF33(10 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_148_p1 <= ap_const_lv26_3FFFE33(10 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_148_p1 <= ap_const_lv25_1FFFF29(10 - 1 downto 0);
            else 
                grp_fu_148_p1 <= "XXXXXXXXXX";
            end if;
        else 
            grp_fu_148_p1 <= "XXXXXXXXXX";
        end if; 
    end process;

    grp_fu_366_p1 <= grp_fu_145_p2(25 - 1 downto 0);
    grp_fu_376_p1 <= grp_fu_148_p2(25 - 1 downto 0);
        sext_ln42_16_fu_768_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(reg_410),16));

        sext_ln42_17_fu_772_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_s_reg_938),16));

        sext_ln42_18_fu_603_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(reg_406),16));

        sext_ln42_19_fu_700_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(reg_410),16));

        sext_ln42_20_fu_704_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_66_reg_837),16));

        sext_ln42_21_fu_607_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_67_reg_866),16));

        sext_ln42_22_fu_707_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(reg_406),16));

    sext_ln42_23_fu_531_p0 <= ap_port_reg_data_3_val;
        sext_ln42_23_fu_531_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln42_23_fu_531_p0),26));

        sext_ln42_24_fu_711_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_70_reg_877),16));

        sext_ln42_25_fu_620_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_4_val_read_reg_849),26));

        sext_ln42_26_fu_714_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_73_reg_913),16));

        sext_ln42_27_fu_717_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_74_reg_918),16));

    sext_ln42_fu_592_p0 <= ap_port_reg_data_0_val;
        sext_ln42_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln42_fu_592_p0),26));

    sext_ln70_21_fu_422_p0 <= data_1_val;
        sext_ln70_21_fu_422_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_21_fu_422_p0),25));

    sext_ln70_22_fu_475_p0 <= ap_port_reg_data_2_val;
        sext_ln70_22_fu_475_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_22_fu_475_p0),26));

    sext_ln70_23_fu_480_p0 <= ap_port_reg_data_2_val;
        sext_ln70_23_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_23_fu_480_p0),25));

    sext_ln70_24_fu_577_p0 <= ap_port_reg_data_4_val;
        sext_ln70_24_fu_577_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_24_fu_577_p0),25));

        sext_ln70_25_fu_468_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_5_val),26));

    sext_ln70_fu_597_p0 <= ap_port_reg_data_0_val;
        sext_ln70_fu_597_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_fu_597_p0),25));

        sext_ln73_10_fu_641_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_9_fu_634_p3),23));

        sext_ln73_11_fu_652_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_s_fu_645_p3),23));

        sext_ln73_5_fu_448_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_4_fu_440_p3),25));

        sext_ln73_6_fu_493_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_5_fu_485_p3),24));

        sext_ln73_7_fu_511_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_6_fu_503_p3),24));

        sext_ln73_8_fu_545_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_7_fu_537_p3),25));

        sext_ln73_9_fu_557_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_8_fu_549_p3),25));

        sext_ln73_fu_436_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_428_p3),25));

    shl_ln73_4_fu_440_p1 <= data_1_val;
    shl_ln73_4_fu_440_p3 <= (shl_ln73_4_fu_440_p1 & ap_const_lv6_0);
    shl_ln73_5_fu_485_p1 <= ap_port_reg_data_2_val;
    shl_ln73_5_fu_485_p3 <= (shl_ln73_5_fu_485_p1 & ap_const_lv7_0);
    shl_ln73_6_fu_503_p1 <= ap_port_reg_data_2_val;
    shl_ln73_6_fu_503_p3 <= (shl_ln73_6_fu_503_p1 & ap_const_lv1_0);
    shl_ln73_7_fu_537_p1 <= ap_port_reg_data_3_val;
    shl_ln73_7_fu_537_p3 <= (shl_ln73_7_fu_537_p1 & ap_const_lv8_0);
    shl_ln73_8_fu_549_p1 <= ap_port_reg_data_3_val;
    shl_ln73_8_fu_549_p3 <= (shl_ln73_8_fu_549_p1 & ap_const_lv2_0);
    shl_ln73_9_fu_634_p3 <= (data_4_val_read_reg_849 & ap_const_lv6_0);
    shl_ln73_s_fu_645_p3 <= (data_4_val_read_reg_849 & ap_const_lv3_0);
    shl_ln_fu_428_p1 <= data_1_val;
    shl_ln_fu_428_p3 <= (shl_ln_fu_428_p1 & ap_const_lv8_0);
    sub_ln73_4_fu_515_p2 <= std_logic_vector(unsigned(sub_ln73_fu_497_p2) - unsigned(sext_ln73_7_fu_511_p1));
    sub_ln73_5_fu_561_p2 <= std_logic_vector(signed(sext_ln73_8_fu_545_p1) - signed(sext_ln73_9_fu_557_p1));
    sub_ln73_fu_497_p2 <= std_logic_vector(unsigned(ap_const_lv24_0) - unsigned(sext_ln73_6_fu_493_p1));
    trunc_ln42_73_fu_624_p1 <= grp_fu_144_p2(25 - 1 downto 0);
    trunc_ln42_s_fu_690_p1 <= grp_fu_146_p2(25 - 1 downto 0);
end behav;
