-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config5_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config5_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln45_fu_52_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_7_fu_48_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_fu_58_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_6_fu_70_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_6_fu_44_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_6_fu_76_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_7_fu_88_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_fu_40_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_7_fu_94_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln45_fu_66_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_6_fu_84_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_7_fu_102_p1 : STD_LOGIC_VECTOR (15 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= zext_ln45_fu_66_p1;
    ap_return_1 <= zext_ln45_6_fu_84_p1;
    ap_return_2 <= zext_ln45_7_fu_102_p1;
    datareg_6_fu_76_p3 <= 
        trunc_ln42_6_fu_44_p1 when (icmp_ln45_6_fu_70_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_7_fu_94_p3 <= 
        trunc_ln42_fu_40_p1 when (icmp_ln45_7_fu_88_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_fu_58_p3 <= 
        trunc_ln42_7_fu_48_p1 when (icmp_ln45_fu_52_p2(0) = '1') else 
        ap_const_lv15_0;
    icmp_ln45_6_fu_70_p2 <= "1" when (signed(data_1_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_7_fu_88_p2 <= "1" when (signed(data_2_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_fu_52_p2 <= "1" when (signed(data_0_val) > signed(ap_const_lv16_0)) else "0";
    trunc_ln42_6_fu_44_p1 <= data_1_val(15 - 1 downto 0);
    trunc_ln42_7_fu_48_p1 <= data_0_val(15 - 1 downto 0);
    trunc_ln42_fu_40_p1 <= data_2_val(15 - 1 downto 0);
    zext_ln45_6_fu_84_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_6_fu_76_p3),16));
    zext_ln45_7_fu_102_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_7_fu_94_p3),16));
    zext_ln45_fu_66_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_fu_58_p3),16));
end behav;
