-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv26_21A : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000011010";
    constant ap_const_lv24_FFFFAF : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111110101111";
    constant ap_const_lv26_3FFFE1D : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111000011101";
    constant ap_const_lv26_3FFFEEB : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111011101011";
    constant ap_const_lv25_1FFFF5A : STD_LOGIC_VECTOR (24 downto 0) := "1111111111111111101011010";
    constant ap_const_lv26_3FFFD39 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110100111001";
    constant ap_const_lv25_1FFFF1A : STD_LOGIC_VECTOR (24 downto 0) := "1111111111111111100011010";
    constant ap_const_lv26_287 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001010000111";
    constant ap_const_lv25_1FFFF52 : STD_LOGIC_VECTOR (24 downto 0) := "1111111111111111101010010";
    constant ap_const_lv26_281 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001010000001";
    constant ap_const_lv24_FFFFA2 : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111110100010";
    constant ap_const_lv25_1FFFF4C : STD_LOGIC_VECTOR (24 downto 0) := "1111111111111111101001100";
    constant ap_const_lv26_3FFFEDC : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111011011100";
    constant ap_const_lv26_155 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000101010101";
    constant ap_const_lv26_3FFFD33 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110100110011";
    constant ap_const_lv26_3FFFCCE : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110011001110";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv16_FF31 : STD_LOGIC_VECTOR (15 downto 0) := "1111111100110001";
    constant ap_const_lv12_FAF : STD_LOGIC_VECTOR (11 downto 0) := "111110101111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv26_0 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal reg_402 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal reg_406 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal reg_410 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_2_val_read_reg_702 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_0_val_read_reg_708 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_fu_414_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln70_reg_714 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln42_fu_419_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_19_fu_426_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_19_reg_727 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln_reg_733 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_48_reg_738 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln70_18_fu_431_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln73_3_fu_437_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_3_reg_749 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln42_59_reg_756 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln42_49_reg_761 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal trunc_ln42_51_reg_766 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_52_reg_771 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln42_53_reg_776 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_54_reg_781 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln70_20_fu_510_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln58_50_fu_518_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_50_reg_792 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_53_fu_524_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_53_reg_797 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln42_55_reg_802 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_57_reg_807 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_60_reg_812 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln58_51_fu_549_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_51_reg_817 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_54_fu_562_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_54_reg_822 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_50_reg_827 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_48_fu_632_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_48_reg_832 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_56_fu_643_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_56_reg_837 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_58_fu_655_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_58_reg_842 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_port_reg_data_1_val : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_112_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_112_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal grp_fu_113_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_113_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_114_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_114_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_115_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_115_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal grp_fu_116_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_116_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_113_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_116_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_115_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_382_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_114_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_112_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_fu_414_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_fu_419_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_19_fu_426_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_18_fu_431_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln73_3_fu_437_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln73_3_fu_443_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln73_4_fu_450_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sub_ln73_3_fu_454_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln42_49_fu_470_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln42_52_fu_480_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln42_54_fu_500_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln73_6_fu_515_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln42_57_fu_533_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln42_12_fu_530_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_49_fu_543_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln58_fu_559_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_52_fu_554_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln_fu_574_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln73_fu_581_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal shl_ln73_2_fu_591_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal sub_ln73_fu_585_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln73_2_fu_598_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sub_ln73_2_fu_602_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln42_14_fu_621_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_fu_627_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_10_fu_568_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_15_fu_624_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_55_fu_637_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_13_fu_618_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_11_fu_571_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_57_fu_649_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_59_fu_660_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_60_fu_665_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_112_ce : STD_LOGIC;
    signal grp_fu_113_ce : STD_LOGIC;
    signal grp_fu_114_ce : STD_LOGIC;
    signal grp_fu_115_ce : STD_LOGIC;
    signal grp_fu_116_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_mul_16s_12s_26_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_11s_26_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;



begin
    mul_16s_12s_26_2_1_U43 : component myproject_mul_16s_12s_26_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_112_p0,
        din1 => grp_fu_112_p1,
        ce => grp_fu_112_ce,
        dout => grp_fu_112_p2);

    mul_16s_11s_26_2_1_U44 : component myproject_mul_16s_11s_26_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_113_p0,
        din1 => grp_fu_113_p1,
        ce => grp_fu_113_ce,
        dout => grp_fu_113_p2);

    mul_16s_12s_26_2_1_U45 : component myproject_mul_16s_12s_26_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_114_p0,
        din1 => grp_fu_114_p1,
        ce => grp_fu_114_ce,
        dout => grp_fu_114_p2);

    mul_16s_12s_26_2_1_U46 : component myproject_mul_16s_12s_26_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_115_p0,
        din1 => grp_fu_115_p1,
        ce => grp_fu_115_ce,
        dout => grp_fu_115_p2);

    mul_16s_11s_26_2_1_U47 : component myproject_mul_16s_11s_26_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_116_p0,
        din1 => grp_fu_116_p1,
        ce => grp_fu_116_ce,
        dout => grp_fu_116_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln58_48_reg_832 <= add_ln58_48_fu_632_p2;
                add_ln58_56_reg_837 <= add_ln58_56_fu_643_p2;
                add_ln58_58_reg_842 <= add_ln58_58_fu_655_p2;
                data_0_val_read_reg_708 <= data_0_val;
                data_2_val_read_reg_702 <= data_2_val;
                sext_ln70_19_reg_727 <= sext_ln70_19_fu_426_p1;
                sext_ln70_reg_714 <= sext_ln70_fu_414_p1;
                trunc_ln42_50_reg_827 <= sub_ln73_2_fu_602_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                add_ln58_50_reg_792 <= add_ln58_50_fu_518_p2;
                add_ln58_53_reg_797 <= add_ln58_53_fu_524_p2;
                trunc_ln42_49_reg_761 <= trunc_ln42_49_fu_470_p1(24 downto 10);
                trunc_ln42_52_reg_771 <= trunc_ln42_52_fu_480_p1(23 downto 10);
                trunc_ln42_53_reg_776 <= grp_fu_114_p2(25 downto 10);
                trunc_ln42_54_reg_781 <= trunc_ln42_54_fu_500_p1(23 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                add_ln58_51_reg_817 <= add_ln58_51_fu_549_p2;
                add_ln58_54_reg_822 <= add_ln58_54_fu_562_p2;
                trunc_ln42_57_reg_807 <= trunc_ln42_57_fu_533_p1(24 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_port_reg_data_1_val <= data_1_val;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_ce)))) then
                reg_402 <= grp_fu_116_p2(25 downto 10);
                reg_410 <= grp_fu_112_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_ce)))) then
                reg_406 <= grp_fu_115_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_ce))) then
                sext_ln73_3_reg_749 <= sext_ln73_3_fu_437_p1;
                trunc_ln42_59_reg_756 <= sub_ln73_3_fu_454_p2(20 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_ce))) then
                trunc_ln42_48_reg_738 <= grp_fu_382_p1(24 downto 10);
                trunc_ln_reg_733 <= grp_fu_113_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                trunc_ln42_51_reg_766 <= grp_fu_116_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                trunc_ln42_55_reg_802 <= grp_fu_113_p2(25 downto 10);
                trunc_ln42_60_reg_812 <= grp_fu_382_p1(24 downto 10);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_block_pp0_stage3_subdone, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_reset_idle_pp0, ap_block_pp0_stage2_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if (((ap_reset_idle_pp0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                elsif (((ap_reset_idle_pp0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln58_48_fu_632_p2 <= std_logic_vector(unsigned(add_ln58_fu_627_p2) + unsigned(trunc_ln42_51_reg_766));
    add_ln58_49_fu_543_p2 <= std_logic_vector(unsigned(reg_402) + unsigned(sext_ln42_12_fu_530_p1));
    add_ln58_50_fu_518_p2 <= std_logic_vector(unsigned(reg_410) + unsigned(ap_const_lv16_FF31));
    add_ln58_51_fu_549_p2 <= std_logic_vector(unsigned(add_ln58_50_reg_792) + unsigned(add_ln58_49_fu_543_p2));
    add_ln58_52_fu_554_p2 <= std_logic_vector(unsigned(reg_406) + unsigned(trunc_ln42_53_reg_776));
    add_ln58_53_fu_524_p2 <= std_logic_vector(signed(sext_ln73_6_fu_515_p1) + signed(ap_const_lv12_FAF));
    add_ln58_54_fu_562_p2 <= std_logic_vector(signed(sext_ln58_fu_559_p1) + signed(add_ln58_52_fu_554_p2));
    add_ln58_55_fu_637_p2 <= std_logic_vector(signed(sext_ln42_10_fu_568_p1) + signed(sext_ln42_15_fu_624_p1));
    add_ln58_56_fu_643_p2 <= std_logic_vector(unsigned(add_ln58_55_fu_637_p2) + unsigned(sext_ln42_13_fu_618_p1));
    add_ln58_57_fu_649_p2 <= std_logic_vector(signed(sext_ln42_11_fu_571_p1) + signed(reg_410));
    add_ln58_58_fu_655_p2 <= std_logic_vector(unsigned(add_ln58_57_fu_649_p2) + unsigned(trunc_ln42_55_reg_802));
    add_ln58_59_fu_660_p2 <= std_logic_vector(unsigned(trunc_ln42_50_reg_827) + unsigned(reg_406));
    add_ln58_60_fu_665_p2 <= std_logic_vector(unsigned(add_ln58_59_fu_660_p2) + unsigned(reg_402));
    add_ln58_fu_627_p2 <= std_logic_vector(unsigned(trunc_ln_reg_733) + unsigned(sext_ln42_14_fu_621_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage1_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage2_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage3_subdone <= (ap_const_logic_0 = ap_ce);
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= add_ln58_48_reg_832;
    ap_return_1 <= add_ln58_51_reg_817;
    ap_return_2 <= add_ln58_54_reg_822;
    ap_return_3 <= add_ln58_56_reg_837;
    ap_return_4 <= add_ln58_58_reg_842;
    ap_return_5 <= add_ln58_60_fu_665_p2;

    grp_fu_112_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage3, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_logic_1 = ap_ce) and (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))))) then 
            grp_fu_112_ce <= ap_const_logic_1;
        else 
            grp_fu_112_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_112_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, sext_ln70_19_fu_426_p1, sext_ln70_19_reg_727, sext_ln70_18_fu_431_p1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_112_p0 <= sext_ln70_19_reg_727(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_112_p0 <= sext_ln70_18_fu_431_p1(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_112_p0 <= sext_ln70_19_fu_426_p1(16 - 1 downto 0);
            else 
                grp_fu_112_p0 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_112_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_112_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_112_p1 <= ap_const_lv26_3FFFE1D(12 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_112_p1 <= ap_const_lv24_FFFFAF(12 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_112_p1 <= ap_const_lv26_21A(12 - 1 downto 0);
            else 
                grp_fu_112_p1 <= "XXXXXXXXXXXX";
            end if;
        else 
            grp_fu_112_p1 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_113_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage3, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_logic_1 = ap_ce) and (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))))) then 
            grp_fu_113_ce <= ap_const_logic_1;
        else 
            grp_fu_113_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_113_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, sext_ln70_reg_714, sext_ln42_fu_419_p1, sext_ln73_3_reg_749, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_113_p0 <= sext_ln73_3_reg_749(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_113_p0 <= sext_ln70_reg_714(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_113_p0 <= sext_ln42_fu_419_p1(16 - 1 downto 0);
            else 
                grp_fu_113_p0 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_113_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_113_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_113_p1 <= ap_const_lv26_3FFFD39(11 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_113_p1 <= ap_const_lv25_1FFFF5A(11 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_113_p1 <= ap_const_lv26_3FFFEEB(11 - 1 downto 0);
            else 
                grp_fu_113_p1 <= "XXXXXXXXXXX";
            end if;
        else 
            grp_fu_113_p1 <= "XXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_114_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage3, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_logic_1 = ap_ce) and (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))))) then 
            grp_fu_114_ce <= ap_const_logic_1;
        else 
            grp_fu_114_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_114_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, sext_ln70_fu_414_p1, sext_ln73_3_fu_437_p1, ap_CS_fsm_pp0_stage2, sext_ln70_20_fu_510_p1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_114_p0 <= sext_ln70_20_fu_510_p1(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_114_p0 <= sext_ln73_3_fu_437_p1(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_114_p0 <= sext_ln70_fu_414_p1(16 - 1 downto 0);
            else 
                grp_fu_114_p0 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_114_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_114_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_114_p1 <= ap_const_lv25_1FFFF52(12 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_114_p1 <= ap_const_lv26_287(12 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_114_p1 <= ap_const_lv25_1FFFF1A(12 - 1 downto 0);
            else 
                grp_fu_114_p1 <= "XXXXXXXXXXXX";
            end if;
        else 
            grp_fu_114_p1 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_115_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage3, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_logic_1 = ap_ce) and (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))))) then 
            grp_fu_115_ce <= ap_const_logic_1;
        else 
            grp_fu_115_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_115_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, sext_ln42_fu_419_p1, sext_ln70_19_reg_727, sext_ln70_18_fu_431_p1, ap_CS_fsm_pp0_stage2, sext_ln70_20_fu_510_p1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                grp_fu_115_p0 <= sext_ln70_19_reg_727(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_115_p0 <= sext_ln70_20_fu_510_p1(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_115_p0 <= sext_ln70_18_fu_431_p1(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_115_p0 <= sext_ln42_fu_419_p1(16 - 1 downto 0);
            else 
                grp_fu_115_p0 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_115_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_115_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                grp_fu_115_p1 <= ap_const_lv26_3FFFEDC(12 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_115_p1 <= ap_const_lv25_1FFFF4C(12 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_115_p1 <= ap_const_lv24_FFFFA2(12 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_115_p1 <= ap_const_lv26_281(12 - 1 downto 0);
            else 
                grp_fu_115_p1 <= "XXXXXXXXXXXX";
            end if;
        else 
            grp_fu_115_p1 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_116_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage3, ap_ce, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage3_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_logic_1 = ap_ce) and (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))))) then 
            grp_fu_116_ce <= ap_const_logic_1;
        else 
            grp_fu_116_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_116_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, sext_ln42_fu_419_p1, sext_ln73_3_fu_437_p1, sext_ln73_3_reg_749, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_116_p0 <= sext_ln73_3_reg_749(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_116_p0 <= sext_ln73_3_fu_437_p1(16 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_116_p0 <= sext_ln42_fu_419_p1(16 - 1 downto 0);
            else 
                grp_fu_116_p0 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_116_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_116_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_116_p1 <= ap_const_lv26_3FFFCCE(11 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_116_p1 <= ap_const_lv26_3FFFD33(11 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_116_p1 <= ap_const_lv26_155(11 - 1 downto 0);
            else 
                grp_fu_116_p1 <= "XXXXXXXXXXX";
            end if;
        else 
            grp_fu_116_p1 <= "XXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_382_p1 <= grp_fu_114_p2(25 - 1 downto 0);
        sext_ln42_10_fu_568_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_48_reg_738),16));

        sext_ln42_11_fu_571_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_49_reg_761),16));

        sext_ln42_12_fu_530_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_52_reg_771),16));

        sext_ln42_13_fu_618_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_54_reg_781),16));

        sext_ln42_14_fu_621_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_57_reg_807),16));

        sext_ln42_15_fu_624_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_60_reg_812),16));

    sext_ln42_fu_419_p0 <= data_0_val;
        sext_ln42_fu_419_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln42_fu_419_p0),26));

        sext_ln58_fu_559_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_53_reg_797),16));

    sext_ln70_18_fu_431_p0 <= ap_port_reg_data_1_val;
        sext_ln70_18_fu_431_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_18_fu_431_p0),24));

    sext_ln70_19_fu_426_p0 <= data_2_val;
        sext_ln70_19_fu_426_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_19_fu_426_p0),26));

        sext_ln70_20_fu_510_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_2_val_read_reg_702),25));

    sext_ln70_fu_414_p0 <= data_0_val;
        sext_ln70_fu_414_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_fu_414_p0),25));

        sext_ln73_2_fu_598_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_2_fu_591_p3),26));

    sext_ln73_3_fu_437_p0 <= ap_port_reg_data_1_val;
        sext_ln73_3_fu_437_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln73_3_fu_437_p0),26));

        sext_ln73_4_fu_450_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln73_3_fu_443_p3),21));

        sext_ln73_6_fu_515_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_59_reg_756),12));

        sext_ln73_fu_581_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_574_p3),26));

    shl_ln73_2_fu_591_p3 <= (data_0_val_read_reg_708 & ap_const_lv5_0);
    shl_ln73_3_fu_443_p3 <= (data_2_val_read_reg_702 & ap_const_lv4_0);
    shl_ln_fu_574_p3 <= (data_0_val_read_reg_708 & ap_const_lv9_0);
    sub_ln73_2_fu_602_p2 <= std_logic_vector(unsigned(sub_ln73_fu_585_p2) - unsigned(sext_ln73_2_fu_598_p1));
    sub_ln73_3_fu_454_p2 <= std_logic_vector(unsigned(ap_const_lv21_0) - unsigned(sext_ln73_4_fu_450_p1));
    sub_ln73_fu_585_p2 <= std_logic_vector(unsigned(ap_const_lv26_0) - unsigned(sext_ln73_fu_581_p1));
    trunc_ln42_49_fu_470_p1 <= grp_fu_113_p2(25 - 1 downto 0);
    trunc_ln42_52_fu_480_p1 <= grp_fu_115_p2(24 - 1 downto 0);
    trunc_ln42_54_fu_500_p1 <= grp_fu_112_p2(24 - 1 downto 0);
    trunc_ln42_57_fu_533_p1 <= grp_fu_115_p2(25 - 1 downto 0);
end behav;
