// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_0_val,
        data_1_val,
        data_2_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
reg    ap_block_pp0_stage3_subdone;
reg   [15:0] reg_402;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire    ap_block_pp0_stage3_11001;
reg   [15:0] reg_406;
wire    ap_block_pp0_stage0_11001;
reg   [15:0] reg_410;
reg  signed [15:0] data_2_val_read_reg_702;
reg  signed [15:0] data_0_val_read_reg_708;
wire  signed [24:0] sext_ln70_fu_414_p1;
reg  signed [24:0] sext_ln70_reg_714;
wire  signed [25:0] sext_ln42_fu_419_p1;
wire  signed [25:0] sext_ln70_19_fu_426_p1;
reg  signed [25:0] sext_ln70_19_reg_727;
reg   [15:0] trunc_ln_reg_733;
reg   [14:0] trunc_ln42_48_reg_738;
wire  signed [23:0] sext_ln70_18_fu_431_p1;
wire  signed [25:0] sext_ln73_3_fu_437_p1;
reg  signed [25:0] sext_ln73_3_reg_749;
reg   [10:0] trunc_ln42_59_reg_756;
reg   [14:0] trunc_ln42_49_reg_761;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [15:0] trunc_ln42_51_reg_766;
reg   [13:0] trunc_ln42_52_reg_771;
reg   [15:0] trunc_ln42_53_reg_776;
reg   [13:0] trunc_ln42_54_reg_781;
wire  signed [24:0] sext_ln70_20_fu_510_p1;
wire   [15:0] add_ln58_50_fu_518_p2;
reg   [15:0] add_ln58_50_reg_792;
wire   [11:0] add_ln58_53_fu_524_p2;
reg   [11:0] add_ln58_53_reg_797;
reg   [15:0] trunc_ln42_55_reg_802;
reg   [14:0] trunc_ln42_57_reg_807;
reg   [14:0] trunc_ln42_60_reg_812;
wire   [15:0] add_ln58_51_fu_549_p2;
reg   [15:0] add_ln58_51_reg_817;
wire   [15:0] add_ln58_54_fu_562_p2;
reg   [15:0] add_ln58_54_reg_822;
reg   [15:0] trunc_ln42_50_reg_827;
wire   [15:0] add_ln58_48_fu_632_p2;
reg   [15:0] add_ln58_48_reg_832;
wire   [15:0] add_ln58_56_fu_643_p2;
reg   [15:0] add_ln58_56_reg_837;
wire   [15:0] add_ln58_58_fu_655_p2;
reg   [15:0] add_ln58_58_reg_842;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone;
reg   [15:0] ap_port_reg_data_1_val;
reg  signed [15:0] grp_fu_112_p0;
reg  signed [11:0] grp_fu_112_p1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage2;
reg  signed [15:0] grp_fu_113_p0;
reg  signed [10:0] grp_fu_113_p1;
reg  signed [15:0] grp_fu_114_p0;
reg  signed [11:0] grp_fu_114_p1;
reg  signed [15:0] grp_fu_115_p0;
reg  signed [11:0] grp_fu_115_p1;
wire    ap_block_pp0_stage3;
reg  signed [15:0] grp_fu_116_p0;
reg  signed [10:0] grp_fu_116_p1;
wire   [25:0] grp_fu_113_p2;
wire   [25:0] grp_fu_116_p2;
wire   [25:0] grp_fu_115_p2;
wire   [24:0] grp_fu_382_p1;
wire   [25:0] grp_fu_114_p2;
wire   [25:0] grp_fu_112_p2;
wire  signed [15:0] sext_ln70_fu_414_p0;
wire  signed [15:0] sext_ln42_fu_419_p0;
wire  signed [15:0] sext_ln70_19_fu_426_p0;
wire  signed [15:0] sext_ln70_18_fu_431_p0;
wire  signed [15:0] sext_ln73_3_fu_437_p0;
wire   [19:0] shl_ln73_3_fu_443_p3;
wire  signed [20:0] sext_ln73_4_fu_450_p1;
wire   [20:0] sub_ln73_3_fu_454_p2;
wire   [24:0] trunc_ln42_49_fu_470_p1;
wire   [23:0] trunc_ln42_52_fu_480_p1;
wire   [23:0] trunc_ln42_54_fu_500_p1;
wire  signed [11:0] sext_ln73_6_fu_515_p1;
wire   [24:0] trunc_ln42_57_fu_533_p1;
wire  signed [15:0] sext_ln42_12_fu_530_p1;
wire   [15:0] add_ln58_49_fu_543_p2;
wire  signed [15:0] sext_ln58_fu_559_p1;
wire   [15:0] add_ln58_52_fu_554_p2;
wire   [24:0] shl_ln_fu_574_p3;
wire  signed [25:0] sext_ln73_fu_581_p1;
wire   [20:0] shl_ln73_2_fu_591_p3;
wire   [25:0] sub_ln73_fu_585_p2;
wire  signed [25:0] sext_ln73_2_fu_598_p1;
wire   [25:0] sub_ln73_2_fu_602_p2;
wire  signed [15:0] sext_ln42_14_fu_621_p1;
wire   [15:0] add_ln58_fu_627_p2;
wire  signed [15:0] sext_ln42_10_fu_568_p1;
wire  signed [15:0] sext_ln42_15_fu_624_p1;
wire   [15:0] add_ln58_55_fu_637_p2;
wire  signed [15:0] sext_ln42_13_fu_618_p1;
wire  signed [15:0] sext_ln42_11_fu_571_p1;
wire   [15:0] add_ln58_57_fu_649_p2;
wire   [15:0] add_ln58_59_fu_660_p2;
wire   [15:0] add_ln58_60_fu_665_p2;
reg    grp_fu_112_ce;
reg    grp_fu_113_ce;
reg    grp_fu_114_ce;
reg    grp_fu_115_ce;
reg    grp_fu_116_ce;
reg   [3:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

myproject_mul_16s_12s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_112_p0),
    .din1(grp_fu_112_p1),
    .ce(grp_fu_112_ce),
    .dout(grp_fu_112_p2)
);

myproject_mul_16s_11s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_113_p0),
    .din1(grp_fu_113_p1),
    .ce(grp_fu_113_ce),
    .dout(grp_fu_113_p2)
);

myproject_mul_16s_12s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_114_p0),
    .din1(grp_fu_114_p1),
    .ce(grp_fu_114_ce),
    .dout(grp_fu_114_p2)
);

myproject_mul_16s_12s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_115_p0),
    .din1(grp_fu_115_p1),
    .ce(grp_fu_115_ce),
    .dout(grp_fu_115_p2)
);

myproject_mul_16s_11s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_1_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_116_p0),
    .din1(grp_fu_116_p1),
    .ce(grp_fu_116_ce),
    .dout(grp_fu_116_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln58_48_reg_832 <= add_ln58_48_fu_632_p2;
        add_ln58_56_reg_837 <= add_ln58_56_fu_643_p2;
        add_ln58_58_reg_842 <= add_ln58_58_fu_655_p2;
        data_0_val_read_reg_708 <= data_0_val;
        data_2_val_read_reg_702 <= data_2_val;
        sext_ln70_19_reg_727 <= sext_ln70_19_fu_426_p1;
        sext_ln70_reg_714 <= sext_ln70_fu_414_p1;
        trunc_ln42_50_reg_827 <= {{sub_ln73_2_fu_602_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln58_50_reg_792 <= add_ln58_50_fu_518_p2;
        add_ln58_53_reg_797 <= add_ln58_53_fu_524_p2;
        trunc_ln42_49_reg_761 <= {{trunc_ln42_49_fu_470_p1[24:10]}};
        trunc_ln42_52_reg_771 <= {{trunc_ln42_52_fu_480_p1[23:10]}};
        trunc_ln42_53_reg_776 <= {{grp_fu_114_p2[25:10]}};
        trunc_ln42_54_reg_781 <= {{trunc_ln42_54_fu_500_p1[23:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln58_51_reg_817 <= add_ln58_51_fu_549_p2;
        add_ln58_54_reg_822 <= add_ln58_54_fu_562_p2;
        trunc_ln42_57_reg_807 <= {{trunc_ln42_57_fu_533_p1[24:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_port_reg_data_1_val <= data_1_val;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce)))) begin
        reg_402 <= {{grp_fu_116_p2[25:10]}};
        reg_410 <= {{grp_fu_112_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce)))) begin
        reg_406 <= {{grp_fu_115_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        sext_ln73_3_reg_749 <= sext_ln73_3_fu_437_p1;
        trunc_ln42_59_reg_756 <= {{sub_ln73_3_fu_454_p2[20:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        trunc_ln42_48_reg_738 <= {{grp_fu_382_p1[24:10]}};
        trunc_ln_reg_733 <= {{grp_fu_113_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        trunc_ln42_51_reg_766 <= {{grp_fu_116_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        trunc_ln42_55_reg_802 <= {{grp_fu_113_p2[25:10]}};
        trunc_ln42_60_reg_812 <= {{grp_fu_382_p1[24:10]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_112_ce = 1'b1;
    end else begin
        grp_fu_112_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_112_p0 = sext_ln70_19_reg_727;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_112_p0 = sext_ln70_18_fu_431_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_112_p0 = sext_ln70_19_fu_426_p1;
        end else begin
            grp_fu_112_p0 = 'bx;
        end
    end else begin
        grp_fu_112_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_112_p1 = 26'd67108381;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_112_p1 = 24'd16777135;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_112_p1 = 26'd538;
        end else begin
            grp_fu_112_p1 = 'bx;
        end
    end else begin
        grp_fu_112_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_113_ce = 1'b1;
    end else begin
        grp_fu_113_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_113_p0 = sext_ln73_3_reg_749;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_113_p0 = sext_ln70_reg_714;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_113_p0 = sext_ln42_fu_419_p1;
        end else begin
            grp_fu_113_p0 = 'bx;
        end
    end else begin
        grp_fu_113_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_113_p1 = 26'd67108153;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_113_p1 = 25'd33554266;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_113_p1 = 26'd67108587;
        end else begin
            grp_fu_113_p1 = 'bx;
        end
    end else begin
        grp_fu_113_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_114_ce = 1'b1;
    end else begin
        grp_fu_114_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_114_p0 = sext_ln70_20_fu_510_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_114_p0 = sext_ln73_3_fu_437_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_114_p0 = sext_ln70_fu_414_p1;
        end else begin
            grp_fu_114_p0 = 'bx;
        end
    end else begin
        grp_fu_114_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_114_p1 = 25'd33554258;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_114_p1 = 26'd647;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_114_p1 = 25'd33554202;
        end else begin
            grp_fu_114_p1 = 'bx;
        end
    end else begin
        grp_fu_114_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_115_ce = 1'b1;
    end else begin
        grp_fu_115_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_115_p0 = sext_ln70_19_reg_727;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_115_p0 = sext_ln70_20_fu_510_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_115_p0 = sext_ln70_18_fu_431_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_115_p0 = sext_ln42_fu_419_p1;
        end else begin
            grp_fu_115_p0 = 'bx;
        end
    end else begin
        grp_fu_115_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_115_p1 = 26'd67108572;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_115_p1 = 25'd33554252;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_115_p1 = 24'd16777122;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_115_p1 = 26'd641;
        end else begin
            grp_fu_115_p1 = 'bx;
        end
    end else begin
        grp_fu_115_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_116_ce = 1'b1;
    end else begin
        grp_fu_116_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_116_p0 = sext_ln73_3_reg_749;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_116_p0 = sext_ln73_3_fu_437_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_116_p0 = sext_ln42_fu_419_p1;
        end else begin
            grp_fu_116_p0 = 'bx;
        end
    end else begin
        grp_fu_116_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_116_p1 = 26'd67108046;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_116_p1 = 26'd67108147;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_116_p1 = 26'd341;
        end else begin
            grp_fu_116_p1 = 'bx;
        end
    end else begin
        grp_fu_116_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_reset_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_48_fu_632_p2 = (add_ln58_fu_627_p2 + trunc_ln42_51_reg_766);

assign add_ln58_49_fu_543_p2 = ($signed(reg_402) + $signed(sext_ln42_12_fu_530_p1));

assign add_ln58_50_fu_518_p2 = ($signed(reg_410) + $signed(16'd65329));

assign add_ln58_51_fu_549_p2 = (add_ln58_50_reg_792 + add_ln58_49_fu_543_p2);

assign add_ln58_52_fu_554_p2 = (reg_406 + trunc_ln42_53_reg_776);

assign add_ln58_53_fu_524_p2 = ($signed(sext_ln73_6_fu_515_p1) + $signed(12'd4015));

assign add_ln58_54_fu_562_p2 = ($signed(sext_ln58_fu_559_p1) + $signed(add_ln58_52_fu_554_p2));

assign add_ln58_55_fu_637_p2 = ($signed(sext_ln42_10_fu_568_p1) + $signed(sext_ln42_15_fu_624_p1));

assign add_ln58_56_fu_643_p2 = ($signed(add_ln58_55_fu_637_p2) + $signed(sext_ln42_13_fu_618_p1));

assign add_ln58_57_fu_649_p2 = ($signed(sext_ln42_11_fu_571_p1) + $signed(reg_410));

assign add_ln58_58_fu_655_p2 = (add_ln58_57_fu_649_p2 + trunc_ln42_55_reg_802);

assign add_ln58_59_fu_660_p2 = (trunc_ln42_50_reg_827 + reg_406);

assign add_ln58_60_fu_665_p2 = (add_ln58_59_fu_660_p2 + reg_402);

assign add_ln58_fu_627_p2 = ($signed(trunc_ln_reg_733) + $signed(sext_ln42_14_fu_621_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return_0 = add_ln58_48_reg_832;

assign ap_return_1 = add_ln58_51_reg_817;

assign ap_return_2 = add_ln58_54_reg_822;

assign ap_return_3 = add_ln58_56_reg_837;

assign ap_return_4 = add_ln58_58_reg_842;

assign ap_return_5 = add_ln58_60_fu_665_p2;

assign grp_fu_382_p1 = grp_fu_114_p2;

assign sext_ln42_10_fu_568_p1 = $signed(trunc_ln42_48_reg_738);

assign sext_ln42_11_fu_571_p1 = $signed(trunc_ln42_49_reg_761);

assign sext_ln42_12_fu_530_p1 = $signed(trunc_ln42_52_reg_771);

assign sext_ln42_13_fu_618_p1 = $signed(trunc_ln42_54_reg_781);

assign sext_ln42_14_fu_621_p1 = $signed(trunc_ln42_57_reg_807);

assign sext_ln42_15_fu_624_p1 = $signed(trunc_ln42_60_reg_812);

assign sext_ln42_fu_419_p0 = data_0_val;

assign sext_ln42_fu_419_p1 = sext_ln42_fu_419_p0;

assign sext_ln58_fu_559_p1 = $signed(add_ln58_53_reg_797);

assign sext_ln70_18_fu_431_p0 = ap_port_reg_data_1_val;

assign sext_ln70_18_fu_431_p1 = sext_ln70_18_fu_431_p0;

assign sext_ln70_19_fu_426_p0 = data_2_val;

assign sext_ln70_19_fu_426_p1 = sext_ln70_19_fu_426_p0;

assign sext_ln70_20_fu_510_p1 = data_2_val_read_reg_702;

assign sext_ln70_fu_414_p0 = data_0_val;

assign sext_ln70_fu_414_p1 = sext_ln70_fu_414_p0;

assign sext_ln73_2_fu_598_p1 = $signed(shl_ln73_2_fu_591_p3);

assign sext_ln73_3_fu_437_p0 = ap_port_reg_data_1_val;

assign sext_ln73_3_fu_437_p1 = sext_ln73_3_fu_437_p0;

assign sext_ln73_4_fu_450_p1 = $signed(shl_ln73_3_fu_443_p3);

assign sext_ln73_6_fu_515_p1 = $signed(trunc_ln42_59_reg_756);

assign sext_ln73_fu_581_p1 = $signed(shl_ln_fu_574_p3);

assign shl_ln73_2_fu_591_p3 = {{data_0_val_read_reg_708}, {5'd0}};

assign shl_ln73_3_fu_443_p3 = {{data_2_val_read_reg_702}, {4'd0}};

assign shl_ln_fu_574_p3 = {{data_0_val_read_reg_708}, {9'd0}};

assign sub_ln73_2_fu_602_p2 = ($signed(sub_ln73_fu_585_p2) - $signed(sext_ln73_2_fu_598_p1));

assign sub_ln73_3_fu_454_p2 = ($signed(21'd0) - $signed(sext_ln73_4_fu_450_p1));

assign sub_ln73_fu_585_p2 = ($signed(26'd0) - $signed(sext_ln73_fu_581_p1));

assign trunc_ln42_49_fu_470_p1 = grp_fu_113_p2;

assign trunc_ln42_52_fu_480_p1 = grp_fu_115_p2;

assign trunc_ln42_54_fu_500_p1 = grp_fu_112_p2;

assign trunc_ln42_57_fu_533_p1 = grp_fu_115_p2;

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s
