// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [127:0] data_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
reg    ap_block_pp0_stage3_subdone;
reg   [13:0] reg_1511;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire    ap_block_pp0_stage3_11001;
reg   [15:0] reg_1515;
wire    ap_block_pp0_stage0_11001;
reg   [14:0] reg_1519;
reg   [14:0] reg_1523;
reg   [13:0] reg_1527;
reg   [13:0] reg_1531;
reg   [15:0] reg_1535;
reg   [15:0] reg_1539;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [15:0] reg_1543;
reg   [13:0] reg_1547;
reg   [13:0] reg_1551;
reg   [14:0] reg_1555;
wire  signed [15:0] a_fu_1559_p1;
reg  signed [15:0] a_reg_2460;
wire  signed [24:0] sext_ln70_26_fu_1563_p1;
reg  signed [24:0] sext_ln70_26_reg_2465;
wire  signed [25:0] sext_ln70_27_fu_1568_p1;
wire  signed [23:0] sext_ln70_28_fu_1573_p1;
reg  signed [23:0] sext_ln70_28_reg_2475;
reg  signed [15:0] a_1_reg_2481;
reg  signed [15:0] a_2_reg_2489;
reg  signed [15:0] a_3_reg_2496;
reg  signed [15:0] a_4_reg_2503;
reg   [7:0] trunc_ln42_104_reg_2509;
reg  signed [15:0] a_5_reg_2514;
wire  signed [25:0] sext_ln70_42_fu_1648_p1;
wire  signed [23:0] sext_ln70_43_fu_1653_p1;
wire  signed [24:0] sext_ln70_44_fu_1659_p1;
reg  signed [24:0] sext_ln70_44_reg_2531;
reg   [13:0] trunc_ln42_117_reg_2537;
wire  signed [23:0] sext_ln70_45_fu_1720_p1;
wire  signed [25:0] sext_ln70_46_fu_1725_p1;
reg   [11:0] trunc_ln42_123_reg_2555;
wire  signed [21:0] sext_ln70_fu_1773_p1;
wire  signed [25:0] sext_ln70_30_fu_1780_p1;
wire  signed [23:0] sext_ln70_31_fu_1785_p1;
reg   [11:0] trunc_ln42_87_reg_2578;
wire  signed [25:0] sext_ln70_33_fu_1818_p1;
wire  signed [24:0] sext_ln70_34_fu_1823_p1;
reg  signed [24:0] sext_ln70_34_reg_2589;
reg   [15:0] trunc_ln42_119_reg_2596;
reg   [15:0] trunc_ln42_120_reg_2601;
wire   [14:0] add_ln58_114_fu_1864_p2;
reg   [14:0] add_ln58_114_reg_2606;
reg   [11:0] trunc_ln42_80_reg_2611;
reg   [13:0] trunc_ln42_81_reg_2616;
reg   [14:0] trunc_ln42_82_reg_2621;
reg   [13:0] trunc_ln42_83_reg_2626;
reg   [15:0] trunc_ln42_84_reg_2631;
reg   [15:0] trunc_ln42_85_reg_2636;
reg   [13:0] trunc_ln42_86_reg_2641;
wire  signed [23:0] sext_ln70_32_fu_1930_p1;
reg   [14:0] trunc_ln42_89_reg_2651;
wire  signed [22:0] sext_ln70_35_fu_1934_p1;
wire  signed [23:0] sext_ln70_36_fu_1938_p1;
wire  signed [24:0] sext_ln70_37_fu_1943_p1;
wire  signed [23:0] sext_ln70_38_fu_1949_p1;
wire  signed [24:0] sext_ln70_39_fu_1955_p1;
reg  signed [24:0] sext_ln70_39_reg_2681;
wire   [15:0] add_ln58_82_fu_1983_p2;
reg   [15:0] add_ln58_82_reg_2687;
wire   [15:0] add_ln58_90_fu_1994_p2;
reg   [15:0] add_ln58_90_reg_2692;
wire   [15:0] add_ln58_98_fu_2006_p2;
reg   [15:0] add_ln58_98_reg_2697;
wire   [15:0] add_ln58_106_fu_2022_p2;
reg   [15:0] add_ln58_106_reg_2702;
wire   [15:0] add_ln58_122_fu_2038_p2;
reg   [15:0] add_ln58_122_reg_2707;
reg   [14:0] trunc_ln42_94_reg_2712;
reg   [14:0] trunc_ln42_97_reg_2717;
reg   [12:0] trunc_ln42_99_reg_2722;
reg   [14:0] trunc_ln42_101_reg_2727;
reg   [13:0] trunc_ln42_102_reg_2732;
reg   [13:0] trunc_ln42_103_reg_2737;
wire  signed [25:0] sext_ln70_40_fu_2124_p1;
wire  signed [23:0] sext_ln70_41_fu_2131_p1;
wire   [14:0] add_ln58_fu_2136_p2;
reg   [14:0] add_ln58_reg_2756;
wire   [15:0] add_ln58_85_fu_2142_p2;
reg   [15:0] add_ln58_85_reg_2761;
wire   [15:0] add_ln58_93_fu_2147_p2;
reg   [15:0] add_ln58_93_reg_2766;
wire   [14:0] add_ln58_101_fu_2152_p2;
reg   [14:0] add_ln58_101_reg_2771;
wire   [14:0] add_ln58_109_fu_2158_p2;
reg   [14:0] add_ln58_109_reg_2776;
wire   [15:0] add_ln58_117_fu_2164_p2;
reg   [15:0] add_ln58_117_reg_2781;
reg   [15:0] trunc_ln42_110_reg_2786;
wire   [15:0] add_ln58_78_fu_2216_p2;
reg   [15:0] add_ln58_78_reg_2791;
wire   [15:0] add_ln58_86_fu_2222_p2;
reg   [15:0] add_ln58_86_reg_2796;
wire   [15:0] add_ln58_94_fu_2228_p2;
reg   [15:0] add_ln58_94_reg_2801;
wire   [15:0] add_ln58_102_fu_2234_p2;
reg   [15:0] add_ln58_102_reg_2806;
wire   [14:0] add_ln58_110_fu_2240_p2;
reg   [14:0] add_ln58_110_reg_2811;
wire   [15:0] add_ln58_118_fu_2246_p2;
reg   [15:0] add_ln58_118_reg_2816;
wire   [15:0] add_ln58_83_fu_2287_p2;
reg   [15:0] add_ln58_83_reg_2821;
wire   [15:0] add_ln58_91_fu_2298_p2;
reg   [15:0] add_ln58_91_reg_2826;
wire   [15:0] add_ln58_99_fu_2309_p2;
reg   [15:0] add_ln58_99_reg_2831;
wire   [15:0] add_ln58_107_fu_2319_p2;
reg   [15:0] add_ln58_107_reg_2836;
wire   [15:0] add_ln58_115_fu_2337_p2;
reg   [15:0] add_ln58_115_reg_2841;
wire   [15:0] add_ln58_123_fu_2349_p2;
reg   [15:0] add_ln58_123_reg_2846;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage2_subdone;
reg  signed [15:0] grp_fu_198_p0;
reg  signed [9:0] grp_fu_198_p1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage3;
reg  signed [15:0] grp_fu_199_p0;
reg  signed [10:0] grp_fu_199_p1;
reg  signed [15:0] grp_fu_200_p0;
reg  signed [9:0] grp_fu_200_p1;
reg  signed [15:0] grp_fu_201_p0;
reg  signed [11:0] grp_fu_201_p1;
reg  signed [15:0] grp_fu_202_p0;
reg  signed [8:0] grp_fu_202_p1;
reg  signed [15:0] grp_fu_203_p0;
reg  signed [10:0] grp_fu_203_p1;
reg  signed [15:0] grp_fu_204_p0;
reg  signed [9:0] grp_fu_204_p1;
reg  signed [15:0] grp_fu_205_p0;
reg  signed [7:0] grp_fu_205_p1;
reg  signed [15:0] grp_fu_206_p0;
reg  signed [10:0] grp_fu_206_p1;
reg  signed [15:0] grp_fu_207_p0;
reg   [9:0] grp_fu_207_p1;
reg  signed [15:0] grp_fu_208_p0;
reg  signed [11:0] grp_fu_208_p1;
reg  signed [15:0] grp_fu_209_p0;
reg  signed [10:0] grp_fu_209_p1;
wire   [23:0] grp_fu_205_p2;
wire   [25:0] grp_fu_208_p2;
wire   [24:0] grp_fu_1401_p1;
wire   [25:0] grp_fu_201_p2;
wire   [24:0] grp_fu_202_p2;
wire   [23:0] grp_fu_1421_p1;
wire   [25:0] grp_fu_198_p2;
wire   [23:0] grp_fu_1431_p1;
wire   [25:0] grp_fu_206_p2;
wire   [25:0] grp_fu_203_p2;
wire   [25:0] grp_fu_204_p2;
wire   [25:0] grp_fu_209_p2;
wire   [23:0] grp_fu_1471_p1;
wire   [24:0] grp_fu_200_p2;
wire   [23:0] grp_fu_1481_p1;
wire   [25:0] grp_fu_207_p2;
wire   [24:0] grp_fu_1491_p1;
wire   [25:0] grp_fu_199_p2;
wire  signed [15:0] a_6_fu_1638_p4;
wire   [22:0] shl_ln_fu_1664_p3;
wire  signed [23:0] sext_ln73_13_fu_1672_p1;
wire   [16:0] shl_ln73_s_fu_1682_p3;
wire   [23:0] sub_ln73_fu_1676_p2;
wire  signed [23:0] sext_ln73_14_fu_1690_p1;
wire   [23:0] sub_ln73_6_fu_1694_p2;
wire  signed [15:0] a_7_fu_1710_p4;
wire   [20:0] shl_ln73_1_fu_1733_p3;
wire   [17:0] shl_ln73_2_fu_1745_p3;
wire  signed [21:0] sext_ln73_15_fu_1741_p1;
wire  signed [21:0] sext_ln73_16_fu_1753_p1;
wire   [21:0] add_ln73_fu_1757_p2;
wire   [20:0] tmp_1_fu_1791_p3;
wire  signed [21:0] sext_ln70_29_fu_1777_p1;
wire  signed [21:0] sext_ln73_12_fu_1798_p1;
wire   [21:0] sub_ln73_7_fu_1802_p2;
wire  signed [12:0] sext_ln73_28_fu_1851_p1;
wire   [12:0] add_ln58_113_fu_1854_p2;
wire  signed [14:0] sext_ln58_8_fu_1860_p1;
wire  signed [14:0] sext_ln73_27_fu_1828_p1;
wire   [21:0] trunc_ln42_80_fu_1870_p1;
wire   [23:0] trunc_ln42_81_fu_1880_p1;
wire   [23:0] trunc_ln42_83_fu_1890_p1;
wire   [23:0] trunc_ln42_86_fu_1920_p1;
wire   [15:0] add_ln58_81_fu_1978_p2;
wire  signed [15:0] sext_ln42_43_fu_1962_p1;
wire   [15:0] add_ln58_89_fu_1989_p2;
wire  signed [15:0] sext_ln42_44_fu_1966_p1;
wire   [15:0] add_ln58_97_fu_2000_p2;
wire  signed [15:0] sext_ln42_45_fu_1970_p1;
wire  signed [10:0] sext_ln73_fu_1959_p1;
wire   [10:0] add_ln58_105_fu_2012_p2;
wire   [15:0] zext_ln58_fu_2018_p1;
wire  signed [14:0] sext_ln58_fu_1974_p1;
wire   [14:0] add_ln58_121_fu_2028_p2;
wire  signed [15:0] sext_ln58_10_fu_2034_p1;
wire   [24:0] trunc_ln42_94_fu_2074_p1;
wire   [24:0] trunc_ln42_97_fu_2084_p1;
wire   [22:0] trunc_ln42_99_fu_2094_p1;
wire   [23:0] trunc_ln42_102_fu_2104_p1;
wire   [23:0] trunc_ln42_103_fu_2114_p1;
wire  signed [14:0] sext_ln73_17_fu_2044_p1;
wire  signed [14:0] sext_ln73_20_fu_2061_p1;
wire  signed [15:0] sext_ln42_fu_2048_p1;
wire  signed [14:0] sext_ln73_18_fu_2052_p1;
wire  signed [14:0] sext_ln73_21_fu_2064_p1;
wire  signed [14:0] sext_ln73_19_fu_2055_p1;
wire  signed [14:0] sext_ln73_22_fu_2067_p1;
wire  signed [15:0] sext_ln42_28_fu_2058_p1;
wire  signed [15:0] sext_ln42_29_fu_2070_p1;
wire  signed [15:0] sext_ln42_30_fu_2170_p1;
wire  signed [15:0] sext_ln42_33_fu_2184_p1;
wire  signed [15:0] sext_ln42_34_fu_2188_p1;
wire  signed [15:0] sext_ln42_35_fu_2192_p1;
wire  signed [15:0] sext_ln42_31_fu_2173_p1;
wire  signed [15:0] sext_ln42_36_fu_2195_p1;
wire  signed [14:0] sext_ln73_23_fu_2177_p1;
wire  signed [14:0] sext_ln73_24_fu_2199_p1;
wire  signed [15:0] sext_ln42_32_fu_2181_p1;
wire  signed [15:0] sext_ln42_37_fu_2202_p1;
wire  signed [15:0] sext_ln42_38_fu_2252_p1;
wire  signed [15:0] sext_ln42_42_fu_2269_p1;
wire   [15:0] add_ln58_80_fu_2281_p2;
wire  signed [15:0] sext_ln42_39_fu_2255_p1;
wire   [15:0] add_ln58_88_fu_2292_p2;
wire  signed [15:0] sext_ln42_40_fu_2258_p1;
wire   [15:0] add_ln58_96_fu_2303_p2;
wire  signed [15:0] sext_ln42_46_fu_2277_p1;
wire   [15:0] add_ln58_104_fu_2314_p2;
wire  signed [14:0] sext_ln73_25_fu_2261_p1;
wire  signed [14:0] sext_ln73_26_fu_2273_p1;
wire   [14:0] add_ln58_112_fu_2324_p2;
wire  signed [15:0] sext_ln58_9_fu_2334_p1;
wire  signed [15:0] sext_ln58_7_fu_2330_p1;
wire  signed [15:0] sext_ln42_41_fu_2265_p1;
wire   [15:0] add_ln58_120_fu_2343_p2;
wire  signed [15:0] sext_ln58_3_fu_2354_p1;
wire   [15:0] add_ln58_79_fu_2357_p2;
wire   [15:0] add_ln58_87_fu_2367_p2;
wire   [15:0] add_ln58_95_fu_2376_p2;
wire  signed [15:0] sext_ln58_4_fu_2385_p1;
wire   [15:0] add_ln58_103_fu_2388_p2;
wire  signed [15:0] sext_ln58_6_fu_2401_p1;
wire  signed [15:0] sext_ln58_5_fu_2398_p1;
wire   [15:0] add_ln58_111_fu_2404_p2;
wire   [15:0] add_ln58_119_fu_2415_p2;
wire   [15:0] add_ln58_84_fu_2362_p2;
wire   [15:0] add_ln58_92_fu_2371_p2;
wire   [15:0] add_ln58_100_fu_2380_p2;
wire   [15:0] add_ln58_108_fu_2393_p2;
wire   [15:0] add_ln58_116_fu_2410_p2;
wire   [15:0] add_ln58_124_fu_2419_p2;
reg    grp_fu_198_ce;
reg    grp_fu_199_ce;
reg    grp_fu_200_ce;
reg    grp_fu_201_ce;
reg    grp_fu_202_ce;
reg    grp_fu_203_ce;
reg    grp_fu_204_ce;
reg    grp_fu_205_ce;
reg    grp_fu_206_ce;
reg    grp_fu_207_ce;
reg    grp_fu_208_ce;
reg    grp_fu_209_ce;
reg   [3:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

myproject_mul_16s_10s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_198_p0),
    .din1(grp_fu_198_p1),
    .ce(grp_fu_198_ce),
    .dout(grp_fu_198_p2)
);

myproject_mul_16s_11s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_199_p0),
    .din1(grp_fu_199_p1),
    .ce(grp_fu_199_ce),
    .dout(grp_fu_199_p2)
);

myproject_mul_16s_10s_25_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 25 ))
mul_16s_10s_25_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_200_p0),
    .din1(grp_fu_200_p1),
    .ce(grp_fu_200_ce),
    .dout(grp_fu_200_p2)
);

myproject_mul_16s_12s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_201_p0),
    .din1(grp_fu_201_p1),
    .ce(grp_fu_201_ce),
    .dout(grp_fu_201_p2)
);

myproject_mul_16s_9s_25_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_2_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_202_p0),
    .din1(grp_fu_202_p1),
    .ce(grp_fu_202_ce),
    .dout(grp_fu_202_p2)
);

myproject_mul_16s_11s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_203_p0),
    .din1(grp_fu_203_p1),
    .ce(grp_fu_203_ce),
    .dout(grp_fu_203_p2)
);

myproject_mul_16s_10s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_204_p0),
    .din1(grp_fu_204_p1),
    .ce(grp_fu_204_ce),
    .dout(grp_fu_204_p2)
);

myproject_mul_16s_8s_24_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8s_24_2_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_205_p0),
    .din1(grp_fu_205_p1),
    .ce(grp_fu_205_ce),
    .dout(grp_fu_205_p2)
);

myproject_mul_16s_11s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_206_p0),
    .din1(grp_fu_206_p1),
    .ce(grp_fu_206_ce),
    .dout(grp_fu_206_p2)
);

myproject_mul_16s_10ns_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_2_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_207_p0),
    .din1(grp_fu_207_p1),
    .ce(grp_fu_207_ce),
    .dout(grp_fu_207_p2)
);

myproject_mul_16s_12s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_208_p0),
    .din1(grp_fu_208_p1),
    .ce(grp_fu_208_ce),
    .dout(grp_fu_208_p2)
);

myproject_mul_16s_11s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_209_p0),
    .din1(grp_fu_209_p1),
    .ce(grp_fu_209_ce),
    .dout(grp_fu_209_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_1_reg_2481 <= {{data_val[31:16]}};
        a_2_reg_2489 <= {{data_val[47:32]}};
        a_3_reg_2496 <= {{data_val[63:48]}};
        a_4_reg_2503 <= {{data_val[79:64]}};
        a_5_reg_2514 <= {{data_val[95:80]}};
        a_reg_2460 <= a_fu_1559_p1;
        add_ln58_102_reg_2806 <= add_ln58_102_fu_2234_p2;
        add_ln58_110_reg_2811 <= add_ln58_110_fu_2240_p2;
        add_ln58_118_reg_2816 <= add_ln58_118_fu_2246_p2;
        add_ln58_78_reg_2791 <= add_ln58_78_fu_2216_p2;
        add_ln58_86_reg_2796 <= add_ln58_86_fu_2222_p2;
        add_ln58_94_reg_2801 <= add_ln58_94_fu_2228_p2;
        sext_ln70_26_reg_2465 <= sext_ln70_26_fu_1563_p1;
        sext_ln70_28_reg_2475 <= sext_ln70_28_fu_1573_p1;
        sext_ln70_44_reg_2531 <= sext_ln70_44_fu_1659_p1;
        trunc_ln42_104_reg_2509 <= {{data_val[79:72]}};
        trunc_ln42_110_reg_2786 <= {{grp_fu_201_p2[25:10]}};
        trunc_ln42_117_reg_2537 <= {{sub_ln73_6_fu_1694_p2[23:10]}};
        trunc_ln42_123_reg_2555 <= {{add_ln73_fu_1757_p2[21:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln58_101_reg_2771 <= add_ln58_101_fu_2152_p2;
        add_ln58_109_reg_2776 <= add_ln58_109_fu_2158_p2;
        add_ln58_117_reg_2781 <= add_ln58_117_fu_2164_p2;
        add_ln58_85_reg_2761 <= add_ln58_85_fu_2142_p2;
        add_ln58_93_reg_2766 <= add_ln58_93_fu_2147_p2;
        add_ln58_reg_2756 <= add_ln58_fu_2136_p2;
        trunc_ln42_102_reg_2732 <= {{trunc_ln42_102_fu_2104_p1[23:10]}};
        trunc_ln42_103_reg_2737 <= {{trunc_ln42_103_fu_2114_p1[23:10]}};
        trunc_ln42_94_reg_2712 <= {{trunc_ln42_94_fu_2074_p1[24:10]}};
        trunc_ln42_97_reg_2717 <= {{trunc_ln42_97_fu_2084_p1[24:10]}};
        trunc_ln42_99_reg_2722 <= {{trunc_ln42_99_fu_2094_p1[22:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln58_106_reg_2702 <= add_ln58_106_fu_2022_p2;
        add_ln58_122_reg_2707 <= add_ln58_122_fu_2038_p2;
        add_ln58_82_reg_2687 <= add_ln58_82_fu_1983_p2;
        add_ln58_90_reg_2692 <= add_ln58_90_fu_1994_p2;
        add_ln58_98_reg_2697 <= add_ln58_98_fu_2006_p2;
        sext_ln70_39_reg_2681 <= sext_ln70_39_fu_1955_p1;
        trunc_ln42_80_reg_2611 <= {{trunc_ln42_80_fu_1870_p1[21:10]}};
        trunc_ln42_81_reg_2616 <= {{trunc_ln42_81_fu_1880_p1[23:10]}};
        trunc_ln42_83_reg_2626 <= {{trunc_ln42_83_fu_1890_p1[23:10]}};
        trunc_ln42_84_reg_2631 <= {{grp_fu_198_p2[25:10]}};
        trunc_ln42_85_reg_2636 <= {{grp_fu_206_p2[25:10]}};
        trunc_ln42_86_reg_2641 <= {{trunc_ln42_86_fu_1920_p1[23:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        add_ln58_107_reg_2836 <= add_ln58_107_fu_2319_p2;
        add_ln58_114_reg_2606 <= add_ln58_114_fu_1864_p2;
        add_ln58_115_reg_2841 <= add_ln58_115_fu_2337_p2;
        add_ln58_123_reg_2846 <= add_ln58_123_fu_2349_p2;
        add_ln58_83_reg_2821 <= add_ln58_83_fu_2287_p2;
        add_ln58_91_reg_2826 <= add_ln58_91_fu_2298_p2;
        add_ln58_99_reg_2831 <= add_ln58_99_fu_2309_p2;
        sext_ln70_34_reg_2589 <= sext_ln70_34_fu_1823_p1;
        trunc_ln42_119_reg_2596 <= {{grp_fu_207_p2[25:10]}};
        trunc_ln42_120_reg_2601 <= {{grp_fu_199_p2[25:10]}};
        trunc_ln42_87_reg_2578 <= {{sub_ln73_7_fu_1802_p2[21:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce)))) begin
        reg_1511 <= {{grp_fu_205_p2[23:10]}};
        reg_1519 <= {{grp_fu_1401_p1[24:10]}};
        reg_1547 <= {{grp_fu_1471_p1[23:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce)))) begin
        reg_1515 <= {{grp_fu_208_p2[25:10]}};
        reg_1527 <= {{grp_fu_1421_p1[23:10]}};
        reg_1535 <= {{grp_fu_203_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce)))) begin
        reg_1523 <= {{grp_fu_202_p2[24:10]}};
        reg_1531 <= {{grp_fu_1431_p1[23:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_1539 <= {{grp_fu_204_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_1543 <= {{grp_fu_209_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_1551 <= {{grp_fu_1481_p1[23:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_1555 <= {{grp_fu_200_p2[24:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        trunc_ln42_101_reg_2727 <= {{grp_fu_1491_p1[24:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        trunc_ln42_82_reg_2621 <= {{grp_fu_1401_p1[24:10]}};
        trunc_ln42_89_reg_2651 <= {{grp_fu_1491_p1[24:10]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_198_ce = 1'b1;
    end else begin
        grp_fu_198_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_198_p0 = sext_ln70_41_fu_2131_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_198_p0 = sext_ln70_37_fu_1943_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_198_p0 = sext_ln70_30_fu_1780_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_198_p0 = sext_ln70_43_fu_1653_p1;
        end else begin
            grp_fu_198_p0 = 'bx;
        end
    end else begin
        grp_fu_198_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_198_p1 = 24'd121;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_198_p1 = 25'd181;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_198_p1 = 26'd67108522;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_198_p1 = 24'd113;
        end else begin
            grp_fu_198_p1 = 'bx;
        end
    end else begin
        grp_fu_198_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_199_ce = 1'b1;
    end else begin
        grp_fu_199_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_199_p0 = sext_ln70_39_fu_1955_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_199_p0 = sext_ln70_34_fu_1823_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_199_p0 = sext_ln70_46_fu_1725_p1;
        end else begin
            grp_fu_199_p0 = 'bx;
        end
    end else begin
        grp_fu_199_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_199_p1 = 25'd193;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_199_p1 = 25'd33554212;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_199_p1 = 26'd499;
        end else begin
            grp_fu_199_p1 = 'bx;
        end
    end else begin
        grp_fu_199_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_200_ce = 1'b1;
    end else begin
        grp_fu_200_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_200_p0 = sext_ln70_44_reg_2531;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_200_p0 = sext_ln70_38_fu_1949_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_200_p0 = sext_ln70_34_fu_1823_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_200_p0 = sext_ln70_45_fu_1720_p1;
        end else begin
            grp_fu_200_p0 = 'bx;
        end
    end else begin
        grp_fu_200_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_200_p1 = 25'd253;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_200_p1 = 24'd84;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_200_p1 = 25'd33554193;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_200_p1 = 24'd16777107;
        end else begin
            grp_fu_200_p1 = 'bx;
        end
    end else begin
        grp_fu_200_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_201_ce = 1'b1;
    end else begin
        grp_fu_201_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_201_p0 = sext_ln70_40_fu_2124_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_201_p0 = sext_ln70_37_fu_1943_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_201_p0 = sext_ln70_26_reg_2465;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_201_p0 = sext_ln70_26_fu_1563_p1;
        end else begin
            grp_fu_201_p0 = 'bx;
        end
    end else begin
        grp_fu_201_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_201_p1 = 26'd596;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_201_p1 = 25'd33554274;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_201_p1 = 25'd228;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_201_p1 = 25'd216;
        end else begin
            grp_fu_201_p1 = 'bx;
        end
    end else begin
        grp_fu_201_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_202_ce = 1'b1;
    end else begin
        grp_fu_202_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_202_p0 = sext_ln70_39_reg_2681;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_202_p0 = sext_ln70_37_fu_1943_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_202_p0 = sext_ln70_31_fu_1785_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_202_p0 = sext_ln70_44_fu_1659_p1;
        end else begin
            grp_fu_202_p0 = 'bx;
        end
    end else begin
        grp_fu_202_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_202_p1 = 25'd33554214;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_202_p1 = 25'd33554200;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_202_p1 = 24'd16777108;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_202_p1 = 25'd33554249;
        end else begin
            grp_fu_202_p1 = 'bx;
        end
    end else begin
        grp_fu_202_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_203_ce = 1'b1;
    end else begin
        grp_fu_203_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_203_p0 = sext_ln70_40_fu_2124_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_203_p0 = sext_ln70_35_fu_1934_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_203_p0 = sext_ln70_31_fu_1785_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_203_p0 = sext_ln70_42_fu_1648_p1;
        end else begin
            grp_fu_203_p0 = 'bx;
        end
    end else begin
        grp_fu_203_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_203_p1 = 26'd67108331;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_203_p1 = 23'd8388553;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_203_p1 = 24'd16777099;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_203_p1 = 26'd368;
        end else begin
            grp_fu_203_p1 = 'bx;
        end
    end else begin
        grp_fu_203_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_204_ce = 1'b1;
    end else begin
        grp_fu_204_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_204_p0 = sext_ln70_38_fu_1949_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_204_p0 = sext_ln70_33_fu_1818_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_204_p0 = sext_ln70_46_fu_1725_p1;
        end else begin
            grp_fu_204_p0 = 'bx;
        end
    end else begin
        grp_fu_204_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_204_p1 = 24'd119;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_204_p1 = 26'd67108518;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_204_p1 = 26'd67108466;
        end else begin
            grp_fu_204_p1 = 'bx;
        end
    end else begin
        grp_fu_204_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_205_ce = 1'b1;
    end else begin
        grp_fu_205_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_205_p0 = sext_ln70_32_fu_1930_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_205_p0 = sext_ln70_fu_1773_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_205_p0 = sext_ln70_28_fu_1573_p1;
        end else begin
            grp_fu_205_p0 = 'bx;
        end
    end else begin
        grp_fu_205_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_205_p1 = 24'd16777141;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_205_p1 = 22'd26;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_205_p1 = 24'd16777118;
        end else begin
            grp_fu_205_p1 = 'bx;
        end
    end else begin
        grp_fu_205_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_206_ce = 1'b1;
    end else begin
        grp_fu_206_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_206_p0 = sext_ln70_41_fu_2131_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_206_p0 = sext_ln70_36_fu_1938_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_206_p0 = sext_ln70_30_fu_1780_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_206_p0 = sext_ln70_43_fu_1653_p1;
        end else begin
            grp_fu_206_p0 = 'bx;
        end
    end else begin
        grp_fu_206_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_fu_206_p1 = 24'd16777121;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_206_p1 = 26'd271;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_206_p1 = 24'd16777126;
    end else begin
        grp_fu_206_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_207_ce = 1'b1;
    end else begin
        grp_fu_207_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_207_p0 = sext_ln70_36_fu_1938_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_207_p0 = sext_ln70_31_fu_1785_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_207_p0 = sext_ln70_46_fu_1725_p1;
        end else begin
            grp_fu_207_p0 = 'bx;
        end
    end else begin
        grp_fu_207_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_207_p1 = 24'd73;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_207_p1 = 24'd74;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_207_p1 = 26'd373;
        end else begin
            grp_fu_207_p1 = 'bx;
        end
    end else begin
        grp_fu_207_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_208_ce = 1'b1;
    end else begin
        grp_fu_208_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_208_p0 = sext_ln70_40_fu_2124_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_208_p0 = sext_ln70_34_reg_2589;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_208_p0 = sext_ln70_28_reg_2475;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_208_p0 = sext_ln70_27_fu_1568_p1;
        end else begin
            grp_fu_208_p0 = 'bx;
        end
    end else begin
        grp_fu_208_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_208_p1 = 26'd672;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_208_p1 = 25'd131;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_208_p1 = 24'd16777134;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_208_p1 = 26'd67108590;
        end else begin
            grp_fu_208_p1 = 'bx;
        end
    end else begin
        grp_fu_208_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))))) begin
        grp_fu_209_ce = 1'b1;
    end else begin
        grp_fu_209_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_209_p0 = sext_ln70_40_fu_2124_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_209_p0 = sext_ln70_38_fu_1949_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_209_p0 = sext_ln70_33_fu_1818_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_209_p0 = sext_ln70_46_fu_1725_p1;
        end else begin
            grp_fu_209_p0 = 'bx;
        end
    end else begin
        grp_fu_209_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_209_p1 = 26'd325;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_209_p1 = 24'd16777122;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_209_p1 = 26'd274;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_209_p1 = 26'd354;
        end else begin
            grp_fu_209_p1 = 'bx;
        end
    end else begin
        grp_fu_209_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_reset_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_6_fu_1638_p4 = {{data_val[111:96]}};

assign a_7_fu_1710_p4 = {{data_val[127:112]}};

assign a_fu_1559_p1 = data_val[15:0];

assign add_ln58_100_fu_2380_p2 = (add_ln58_99_reg_2831 + add_ln58_95_fu_2376_p2);

assign add_ln58_101_fu_2152_p2 = ($signed(sext_ln73_18_fu_2052_p1) + $signed(sext_ln73_21_fu_2064_p1));

assign add_ln58_102_fu_2234_p2 = ($signed(sext_ln42_31_fu_2173_p1) + $signed(sext_ln42_36_fu_2195_p1));

assign add_ln58_103_fu_2388_p2 = ($signed(add_ln58_102_reg_2806) + $signed(sext_ln58_4_fu_2385_p1));

assign add_ln58_104_fu_2314_p2 = ($signed(trunc_ln42_110_reg_2786) + $signed(sext_ln42_46_fu_2277_p1));

assign add_ln58_105_fu_2012_p2 = ($signed(sext_ln73_fu_1959_p1) + $signed(11'd955));

assign add_ln58_106_fu_2022_p2 = (zext_ln58_fu_2018_p1 + reg_1543);

assign add_ln58_107_fu_2319_p2 = (add_ln58_106_reg_2702 + add_ln58_104_fu_2314_p2);

assign add_ln58_108_fu_2393_p2 = (add_ln58_107_reg_2836 + add_ln58_103_fu_2388_p2);

assign add_ln58_109_fu_2158_p2 = ($signed(sext_ln73_19_fu_2055_p1) + $signed(sext_ln73_22_fu_2067_p1));

assign add_ln58_110_fu_2240_p2 = ($signed(sext_ln73_23_fu_2177_p1) + $signed(sext_ln73_24_fu_2199_p1));

assign add_ln58_111_fu_2404_p2 = ($signed(sext_ln58_6_fu_2401_p1) + $signed(sext_ln58_5_fu_2398_p1));

assign add_ln58_112_fu_2324_p2 = ($signed(sext_ln73_25_fu_2261_p1) + $signed(sext_ln73_26_fu_2273_p1));

assign add_ln58_113_fu_1854_p2 = ($signed(sext_ln73_28_fu_1851_p1) + $signed(13'd7922));

assign add_ln58_114_fu_1864_p2 = ($signed(sext_ln58_8_fu_1860_p1) + $signed(sext_ln73_27_fu_1828_p1));

assign add_ln58_115_fu_2337_p2 = ($signed(sext_ln58_9_fu_2334_p1) + $signed(sext_ln58_7_fu_2330_p1));

assign add_ln58_116_fu_2410_p2 = (add_ln58_115_reg_2841 + add_ln58_111_fu_2404_p2);

assign add_ln58_117_fu_2164_p2 = ($signed(sext_ln42_28_fu_2058_p1) + $signed(sext_ln42_29_fu_2070_p1));

assign add_ln58_118_fu_2246_p2 = ($signed(sext_ln42_32_fu_2181_p1) + $signed(sext_ln42_37_fu_2202_p1));

assign add_ln58_119_fu_2415_p2 = (add_ln58_118_reg_2816 + add_ln58_117_reg_2781);

assign add_ln58_120_fu_2343_p2 = ($signed(sext_ln42_41_fu_2265_p1) + $signed(reg_1543));

assign add_ln58_121_fu_2028_p2 = ($signed(sext_ln58_fu_1974_p1) + $signed(15'd849));

assign add_ln58_122_fu_2038_p2 = ($signed(sext_ln58_10_fu_2034_p1) + $signed(reg_1535));

assign add_ln58_123_fu_2349_p2 = (add_ln58_122_reg_2707 + add_ln58_120_fu_2343_p2);

assign add_ln58_124_fu_2419_p2 = (add_ln58_123_reg_2846 + add_ln58_119_fu_2415_p2);

assign add_ln58_78_fu_2216_p2 = ($signed(sext_ln42_30_fu_2170_p1) + $signed(sext_ln42_33_fu_2184_p1));

assign add_ln58_79_fu_2357_p2 = ($signed(add_ln58_78_reg_2791) + $signed(sext_ln58_3_fu_2354_p1));

assign add_ln58_80_fu_2281_p2 = ($signed(sext_ln42_38_fu_2252_p1) + $signed(sext_ln42_42_fu_2269_p1));

assign add_ln58_81_fu_1978_p2 = (trunc_ln42_119_reg_2596 + 16'd1020);

assign add_ln58_82_fu_1983_p2 = ($signed(add_ln58_81_fu_1978_p2) + $signed(sext_ln42_43_fu_1962_p1));

assign add_ln58_83_fu_2287_p2 = (add_ln58_82_reg_2687 + add_ln58_80_fu_2281_p2);

assign add_ln58_84_fu_2362_p2 = (add_ln58_83_reg_2821 + add_ln58_79_fu_2357_p2);

assign add_ln58_85_fu_2142_p2 = (reg_1515 + trunc_ln42_84_reg_2631);

assign add_ln58_86_fu_2222_p2 = ($signed(reg_1539) + $signed(sext_ln42_34_fu_2188_p1));

assign add_ln58_87_fu_2367_p2 = (add_ln58_86_reg_2796 + add_ln58_85_reg_2761);

assign add_ln58_88_fu_2292_p2 = ($signed(sext_ln42_39_fu_2255_p1) + $signed(reg_1515));

assign add_ln58_89_fu_1989_p2 = (trunc_ln42_120_reg_2601 + 16'd301);

assign add_ln58_90_fu_1994_p2 = ($signed(add_ln58_89_fu_1989_p2) + $signed(sext_ln42_44_fu_1966_p1));

assign add_ln58_91_fu_2298_p2 = (add_ln58_90_reg_2692 + add_ln58_88_fu_2292_p2);

assign add_ln58_92_fu_2371_p2 = (add_ln58_91_reg_2826 + add_ln58_87_fu_2367_p2);

assign add_ln58_93_fu_2147_p2 = ($signed(sext_ln42_fu_2048_p1) + $signed(trunc_ln42_85_reg_2636));

assign add_ln58_94_fu_2228_p2 = ($signed(reg_1543) + $signed(sext_ln42_35_fu_2192_p1));

assign add_ln58_95_fu_2376_p2 = (add_ln58_94_reg_2801 + add_ln58_93_reg_2766);

assign add_ln58_96_fu_2303_p2 = ($signed(sext_ln42_40_fu_2258_p1) + $signed(reg_1535));

assign add_ln58_97_fu_2000_p2 = ($signed(reg_1539) + $signed(16'd65295));

assign add_ln58_98_fu_2006_p2 = ($signed(add_ln58_97_fu_2000_p2) + $signed(sext_ln42_45_fu_1970_p1));

assign add_ln58_99_fu_2309_p2 = (add_ln58_98_reg_2697 + add_ln58_96_fu_2303_p2);

assign add_ln58_fu_2136_p2 = ($signed(sext_ln73_17_fu_2044_p1) + $signed(sext_ln73_20_fu_2061_p1));

assign add_ln73_fu_1757_p2 = ($signed(sext_ln73_15_fu_1741_p1) + $signed(sext_ln73_16_fu_1753_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return_0 = add_ln58_84_fu_2362_p2;

assign ap_return_1 = add_ln58_92_fu_2371_p2;

assign ap_return_2 = add_ln58_100_fu_2380_p2;

assign ap_return_3 = add_ln58_108_fu_2393_p2;

assign ap_return_4 = add_ln58_116_fu_2410_p2;

assign ap_return_5 = add_ln58_124_fu_2419_p2;

assign grp_fu_1401_p1 = grp_fu_201_p2;

assign grp_fu_1421_p1 = grp_fu_198_p2;

assign grp_fu_1431_p1 = grp_fu_206_p2;

assign grp_fu_1471_p1 = grp_fu_200_p2;

assign grp_fu_1481_p1 = grp_fu_207_p2;

assign grp_fu_1491_p1 = grp_fu_199_p2;

assign sext_ln42_28_fu_2058_p1 = $signed(trunc_ln42_82_reg_2621);

assign sext_ln42_29_fu_2070_p1 = $signed(reg_1551);

assign sext_ln42_30_fu_2170_p1 = $signed(trunc_ln42_89_reg_2651);

assign sext_ln42_31_fu_2173_p1 = $signed(reg_1555);

assign sext_ln42_32_fu_2181_p1 = $signed(trunc_ln42_94_reg_2712);

assign sext_ln42_33_fu_2184_p1 = $signed(reg_1519);

assign sext_ln42_34_fu_2188_p1 = $signed(reg_1523);

assign sext_ln42_35_fu_2192_p1 = $signed(trunc_ln42_97_reg_2717);

assign sext_ln42_36_fu_2195_p1 = $signed(reg_1531);

assign sext_ln42_37_fu_2202_p1 = $signed(reg_1551);

assign sext_ln42_38_fu_2252_p1 = $signed(trunc_ln42_101_reg_2727);

assign sext_ln42_39_fu_2255_p1 = $signed(trunc_ln42_102_reg_2732);

assign sext_ln42_40_fu_2258_p1 = $signed(trunc_ln42_103_reg_2737);

assign sext_ln42_41_fu_2265_p1 = $signed(reg_1523);

assign sext_ln42_42_fu_2269_p1 = $signed(reg_1527);

assign sext_ln42_43_fu_1962_p1 = $signed(reg_1523);

assign sext_ln42_44_fu_1966_p1 = $signed(reg_1527);

assign sext_ln42_45_fu_1970_p1 = $signed(reg_1531);

assign sext_ln42_46_fu_2277_p1 = $signed(reg_1555);

assign sext_ln42_fu_2048_p1 = $signed(reg_1519);

assign sext_ln58_10_fu_2034_p1 = $signed(add_ln58_121_fu_2028_p2);

assign sext_ln58_3_fu_2354_p1 = $signed(add_ln58_reg_2756);

assign sext_ln58_4_fu_2385_p1 = $signed(add_ln58_101_reg_2771);

assign sext_ln58_5_fu_2398_p1 = $signed(add_ln58_109_reg_2776);

assign sext_ln58_6_fu_2401_p1 = $signed(add_ln58_110_reg_2811);

assign sext_ln58_7_fu_2330_p1 = $signed(add_ln58_112_fu_2324_p2);

assign sext_ln58_8_fu_1860_p1 = $signed(add_ln58_113_fu_1854_p2);

assign sext_ln58_9_fu_2334_p1 = $signed(add_ln58_114_reg_2606);

assign sext_ln58_fu_1974_p1 = $signed(reg_1547);

assign sext_ln70_26_fu_1563_p1 = a_fu_1559_p1;

assign sext_ln70_27_fu_1568_p1 = a_fu_1559_p1;

assign sext_ln70_28_fu_1573_p1 = a_fu_1559_p1;

assign sext_ln70_29_fu_1777_p1 = a_1_reg_2481;

assign sext_ln70_30_fu_1780_p1 = a_1_reg_2481;

assign sext_ln70_31_fu_1785_p1 = a_1_reg_2481;

assign sext_ln70_32_fu_1930_p1 = a_2_reg_2489;

assign sext_ln70_33_fu_1818_p1 = a_2_reg_2489;

assign sext_ln70_34_fu_1823_p1 = a_2_reg_2489;

assign sext_ln70_35_fu_1934_p1 = a_3_reg_2496;

assign sext_ln70_36_fu_1938_p1 = a_3_reg_2496;

assign sext_ln70_37_fu_1943_p1 = a_3_reg_2496;

assign sext_ln70_38_fu_1949_p1 = a_4_reg_2503;

assign sext_ln70_39_fu_1955_p1 = a_4_reg_2503;

assign sext_ln70_40_fu_2124_p1 = a_5_reg_2514;

assign sext_ln70_41_fu_2131_p1 = a_5_reg_2514;

assign sext_ln70_42_fu_1648_p1 = a_6_fu_1638_p4;

assign sext_ln70_43_fu_1653_p1 = a_6_fu_1638_p4;

assign sext_ln70_44_fu_1659_p1 = a_6_fu_1638_p4;

assign sext_ln70_45_fu_1720_p1 = a_7_fu_1710_p4;

assign sext_ln70_46_fu_1725_p1 = a_7_fu_1710_p4;

assign sext_ln70_fu_1773_p1 = a_reg_2460;

assign sext_ln73_12_fu_1798_p1 = $signed(tmp_1_fu_1791_p3);

assign sext_ln73_13_fu_1672_p1 = $signed(shl_ln_fu_1664_p3);

assign sext_ln73_14_fu_1690_p1 = $signed(shl_ln73_s_fu_1682_p3);

assign sext_ln73_15_fu_1741_p1 = $signed(shl_ln73_1_fu_1733_p3);

assign sext_ln73_16_fu_1753_p1 = $signed(shl_ln73_2_fu_1745_p3);

assign sext_ln73_17_fu_2044_p1 = $signed(reg_1511);

assign sext_ln73_18_fu_2052_p1 = $signed(trunc_ln42_80_reg_2611);

assign sext_ln73_19_fu_2055_p1 = $signed(trunc_ln42_81_reg_2616);

assign sext_ln73_20_fu_2061_p1 = $signed(trunc_ln42_83_reg_2626);

assign sext_ln73_21_fu_2064_p1 = $signed(trunc_ln42_86_reg_2641);

assign sext_ln73_22_fu_2067_p1 = $signed(trunc_ln42_87_reg_2578);

assign sext_ln73_23_fu_2177_p1 = $signed(reg_1511);

assign sext_ln73_24_fu_2199_p1 = $signed(trunc_ln42_99_reg_2722);

assign sext_ln73_25_fu_2261_p1 = $signed(reg_1547);

assign sext_ln73_26_fu_2273_p1 = $signed(reg_1531);

assign sext_ln73_27_fu_1828_p1 = $signed(trunc_ln42_117_reg_2537);

assign sext_ln73_28_fu_1851_p1 = $signed(trunc_ln42_123_reg_2555);

assign sext_ln73_fu_1959_p1 = $signed(trunc_ln42_104_reg_2509);

assign shl_ln73_1_fu_1733_p3 = {{a_7_fu_1710_p4}, {5'd0}};

assign shl_ln73_2_fu_1745_p3 = {{a_7_fu_1710_p4}, {2'd0}};

assign shl_ln73_s_fu_1682_p3 = {{a_6_fu_1638_p4}, {1'd0}};

assign shl_ln_fu_1664_p3 = {{a_6_fu_1638_p4}, {7'd0}};

assign sub_ln73_6_fu_1694_p2 = ($signed(sub_ln73_fu_1676_p2) - $signed(sext_ln73_14_fu_1690_p1));

assign sub_ln73_7_fu_1802_p2 = ($signed(sext_ln70_29_fu_1777_p1) - $signed(sext_ln73_12_fu_1798_p1));

assign sub_ln73_fu_1676_p2 = ($signed(24'd0) - $signed(sext_ln73_13_fu_1672_p1));

assign tmp_1_fu_1791_p3 = {{a_1_reg_2481}, {5'd0}};

assign trunc_ln42_102_fu_2104_p1 = grp_fu_204_p2;

assign trunc_ln42_103_fu_2114_p1 = grp_fu_209_p2;

assign trunc_ln42_80_fu_1870_p1 = grp_fu_205_p2;

assign trunc_ln42_81_fu_1880_p1 = grp_fu_208_p2;

assign trunc_ln42_83_fu_1890_p1 = grp_fu_202_p2;

assign trunc_ln42_86_fu_1920_p1 = grp_fu_203_p2;

assign trunc_ln42_94_fu_2074_p1 = grp_fu_208_p2;

assign trunc_ln42_97_fu_2084_p1 = grp_fu_198_p2;

assign trunc_ln42_99_fu_2094_p1 = grp_fu_203_p2;

assign zext_ln58_fu_2018_p1 = add_ln58_105_fu_2012_p2;

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s
