// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config5_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        ap_return_0,
        ap_return_1,
        ap_return_2
);


output   ap_ready;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;

wire   [0:0] icmp_ln45_fu_52_p2;
wire   [14:0] trunc_ln42_7_fu_48_p1;
wire   [14:0] datareg_fu_58_p3;
wire   [0:0] icmp_ln45_6_fu_70_p2;
wire   [14:0] trunc_ln42_6_fu_44_p1;
wire   [14:0] datareg_6_fu_76_p3;
wire   [0:0] icmp_ln45_7_fu_88_p2;
wire   [14:0] trunc_ln42_fu_40_p1;
wire   [14:0] datareg_7_fu_94_p3;
wire   [15:0] zext_ln45_fu_66_p1;
wire   [15:0] zext_ln45_6_fu_84_p1;
wire   [15:0] zext_ln45_7_fu_102_p1;

assign ap_ready = 1'b1;

assign datareg_6_fu_76_p3 = ((icmp_ln45_6_fu_70_p2[0:0] == 1'b1) ? trunc_ln42_6_fu_44_p1 : 15'd0);

assign datareg_7_fu_94_p3 = ((icmp_ln45_7_fu_88_p2[0:0] == 1'b1) ? trunc_ln42_fu_40_p1 : 15'd0);

assign datareg_fu_58_p3 = ((icmp_ln45_fu_52_p2[0:0] == 1'b1) ? trunc_ln42_7_fu_48_p1 : 15'd0);

assign trunc_ln42_6_fu_44_p1 = data_1_val[14:0];

assign trunc_ln42_7_fu_48_p1 = data_0_val[14:0];

assign trunc_ln42_fu_40_p1 = data_2_val[14:0];

assign zext_ln45_6_fu_84_p1 = datareg_6_fu_76_p3;

assign zext_ln45_7_fu_102_p1 = datareg_7_fu_94_p3;

assign zext_ln45_fu_66_p1 = datareg_fu_58_p3;

assign ap_return_0 = zext_ln45_fu_66_p1;

assign ap_return_1 = zext_ln45_6_fu_84_p1;

assign ap_return_2 = zext_ln45_7_fu_102_p1;

assign icmp_ln45_6_fu_70_p2 = (($signed(data_1_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_7_fu_88_p2 = (($signed(data_2_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_52_p2 = (($signed(data_0_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

endmodule //myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config5_s
