// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        ap_return_0,
        ap_return_1,
        ap_return_2
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
reg    ap_block_pp0_stage3_subdone;
reg   [14:0] reg_406;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [14:0] reg_410;
wire    ap_block_pp0_stage3_11001;
reg   [15:0] reg_414;
reg   [15:0] reg_418;
wire  signed [24:0] sext_ln70_21_fu_422_p1;
wire    ap_block_pp0_stage0_11001;
reg   [14:0] trunc_ln42_66_reg_837;
wire  signed [25:0] sext_ln70_25_fu_468_p1;
reg  signed [15:0] data_4_val_read_reg_849;
wire  signed [25:0] sext_ln70_22_fu_475_p1;
wire  signed [24:0] sext_ln70_23_fu_480_p1;
reg   [13:0] trunc_ln42_67_reg_866;
wire  signed [25:0] sext_ln42_23_fu_531_p1;
reg   [14:0] trunc_ln42_70_reg_877;
wire  signed [24:0] sext_ln70_24_fu_577_p1;
reg   [15:0] trunc_ln42_78_reg_887;
wire  signed [25:0] sext_ln42_fu_592_p1;
wire  signed [24:0] sext_ln70_fu_597_p1;
reg   [15:0] trunc_ln42_69_reg_903;
wire  signed [25:0] sext_ln42_25_fu_620_p1;
reg   [14:0] trunc_ln42_73_reg_913;
reg   [12:0] trunc_ln42_74_reg_918;
wire   [15:0] add_ln58_fu_672_p2;
reg   [15:0] add_ln58_reg_923;
wire   [15:0] add_ln58_63_fu_678_p2;
reg   [15:0] add_ln58_63_reg_928;
wire   [15:0] add_ln58_69_fu_684_p2;
reg   [15:0] add_ln58_69_reg_933;
reg   [14:0] trunc_ln42_s_reg_938;
reg   [15:0] trunc_ln42_75_reg_943;
wire   [15:0] add_ln58_64_fu_736_p2;
reg   [15:0] add_ln58_64_reg_948;
wire   [15:0] add_ln58_66_fu_741_p2;
reg   [15:0] add_ln58_66_reg_953;
wire   [15:0] add_ln58_70_fu_753_p2;
reg   [15:0] add_ln58_70_reg_958;
wire   [15:0] add_ln58_72_fu_758_p2;
reg   [15:0] add_ln58_72_reg_963;
wire   [15:0] add_ln58_75_fu_763_p2;
reg   [15:0] add_ln58_75_reg_968;
wire   [15:0] add_ln58_65_fu_780_p2;
reg   [15:0] add_ln58_65_reg_973;
wire   [15:0] add_ln58_71_fu_790_p2;
reg   [15:0] add_ln58_71_reg_978;
wire   [15:0] add_ln58_76_fu_800_p2;
reg   [15:0] add_ln58_76_reg_983;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone;
reg   [15:0] ap_port_reg_data_0_val;
reg   [15:0] ap_port_reg_data_2_val;
reg   [15:0] ap_port_reg_data_3_val;
reg   [15:0] ap_port_reg_data_4_val;
reg  signed [15:0] grp_fu_144_p0;
reg  signed [10:0] grp_fu_144_p1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage1;
reg  signed [15:0] grp_fu_145_p0;
reg   [10:0] grp_fu_145_p1;
wire    ap_block_pp0_stage2;
reg  signed [15:0] grp_fu_146_p0;
reg  signed [11:0] grp_fu_146_p1;
reg  signed [15:0] grp_fu_147_p0;
reg   [11:0] grp_fu_147_p1;
reg  signed [15:0] grp_fu_148_p0;
reg  signed [9:0] grp_fu_148_p1;
wire   [24:0] grp_fu_366_p1;
wire   [25:0] grp_fu_145_p2;
wire   [24:0] grp_fu_376_p1;
wire   [25:0] grp_fu_148_p2;
wire    ap_block_pp0_stage3;
wire   [25:0] grp_fu_147_p2;
wire   [25:0] grp_fu_146_p2;
wire  signed [15:0] sext_ln70_21_fu_422_p0;
wire  signed [15:0] shl_ln_fu_428_p1;
wire   [23:0] shl_ln_fu_428_p3;
wire  signed [15:0] shl_ln73_4_fu_440_p1;
wire   [21:0] shl_ln73_4_fu_440_p3;
wire  signed [24:0] sext_ln73_fu_436_p1;
wire  signed [24:0] sext_ln73_5_fu_448_p1;
wire   [24:0] add_ln73_fu_452_p2;
wire  signed [15:0] sext_ln70_22_fu_475_p0;
wire  signed [15:0] sext_ln70_23_fu_480_p0;
wire  signed [15:0] shl_ln73_5_fu_485_p1;
wire   [22:0] shl_ln73_5_fu_485_p3;
wire  signed [23:0] sext_ln73_6_fu_493_p1;
wire  signed [15:0] shl_ln73_6_fu_503_p1;
wire   [16:0] shl_ln73_6_fu_503_p3;
wire   [23:0] sub_ln73_fu_497_p2;
wire  signed [23:0] sext_ln73_7_fu_511_p1;
wire   [23:0] sub_ln73_4_fu_515_p2;
wire  signed [15:0] sext_ln42_23_fu_531_p0;
wire  signed [15:0] shl_ln73_7_fu_537_p1;
wire   [23:0] shl_ln73_7_fu_537_p3;
wire  signed [15:0] shl_ln73_8_fu_549_p1;
wire   [17:0] shl_ln73_8_fu_549_p3;
wire  signed [24:0] sext_ln73_8_fu_545_p1;
wire  signed [24:0] sext_ln73_9_fu_557_p1;
wire   [24:0] sub_ln73_5_fu_561_p2;
wire  signed [15:0] sext_ln70_24_fu_577_p0;
wire   [25:0] grp_fu_144_p2;
wire  signed [15:0] sext_ln42_fu_592_p0;
wire  signed [15:0] sext_ln70_fu_597_p0;
wire   [24:0] trunc_ln42_73_fu_624_p1;
wire   [21:0] shl_ln73_9_fu_634_p3;
wire   [18:0] shl_ln73_s_fu_645_p3;
wire  signed [22:0] sext_ln73_10_fu_641_p1;
wire  signed [22:0] sext_ln73_11_fu_652_p1;
wire   [22:0] add_ln73_1_fu_656_p2;
wire  signed [15:0] sext_ln42_18_fu_603_p1;
wire  signed [15:0] sext_ln42_21_fu_607_p1;
wire   [24:0] trunc_ln42_s_fu_690_p1;
wire  signed [15:0] sext_ln42_24_fu_711_p1;
wire  signed [15:0] sext_ln42_26_fu_714_p1;
wire   [15:0] add_ln58_62_fu_730_p2;
wire  signed [15:0] sext_ln42_19_fu_700_p1;
wire  signed [15:0] sext_ln42_22_fu_707_p1;
wire  signed [15:0] sext_ln42_27_fu_717_p1;
wire   [15:0] add_ln58_68_fu_747_p2;
wire  signed [15:0] sext_ln42_20_fu_704_p1;
wire  signed [15:0] sext_ln42_16_fu_768_p1;
wire   [15:0] add_ln58_61_fu_775_p2;
wire  signed [15:0] sext_ln42_17_fu_772_p1;
wire   [15:0] add_ln58_67_fu_785_p2;
wire   [15:0] add_ln58_74_fu_795_p2;
wire   [15:0] add_ln58_73_fu_805_p2;
wire   [15:0] add_ln58_77_fu_810_p2;
reg    grp_fu_144_ce;
reg    grp_fu_145_ce;
reg    grp_fu_146_ce;
reg    grp_fu_147_ce;
reg    grp_fu_148_ce;
reg   [3:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

myproject_mul_16s_11s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_2_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_144_p0),
    .din1(grp_fu_144_p1),
    .ce(grp_fu_144_ce),
    .dout(grp_fu_144_p2)
);

myproject_mul_16s_11ns_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_2_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_145_p0),
    .din1(grp_fu_145_p1),
    .ce(grp_fu_145_ce),
    .dout(grp_fu_145_p2)
);

myproject_mul_16s_12s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_2_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_146_p0),
    .din1(grp_fu_146_p1),
    .ce(grp_fu_146_ce),
    .dout(grp_fu_146_p2)
);

myproject_mul_16s_12ns_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12ns_26_2_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_147_p0),
    .din1(grp_fu_147_p1),
    .ce(grp_fu_147_ce),
    .dout(grp_fu_147_p2)
);

myproject_mul_16s_10s_26_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_2_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_148_p0),
    .din1(grp_fu_148_p1),
    .ce(grp_fu_148_ce),
    .dout(grp_fu_148_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_ce))) begin
        add_ln58_63_reg_928 <= add_ln58_63_fu_678_p2;
        add_ln58_69_reg_933 <= add_ln58_69_fu_684_p2;
        add_ln58_reg_923 <= add_ln58_fu_672_p2;
        trunc_ln42_69_reg_903 <= {{grp_fu_148_p2[25:10]}};
        trunc_ln42_73_reg_913 <= {{trunc_ln42_73_fu_624_p1[24:10]}};
        trunc_ln42_74_reg_918 <= {{add_ln73_1_fu_656_p2[22:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln58_64_reg_948 <= add_ln58_64_fu_736_p2;
        add_ln58_66_reg_953 <= add_ln58_66_fu_741_p2;
        add_ln58_70_reg_958 <= add_ln58_70_fu_753_p2;
        add_ln58_72_reg_963 <= add_ln58_72_fu_758_p2;
        add_ln58_75_reg_968 <= add_ln58_75_fu_763_p2;
        trunc_ln42_75_reg_943 <= {{grp_fu_145_p2[25:10]}};
        trunc_ln42_s_reg_938 <= {{trunc_ln42_s_fu_690_p1[24:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln58_65_reg_973 <= add_ln58_65_fu_780_p2;
        add_ln58_71_reg_978 <= add_ln58_71_fu_790_p2;
        add_ln58_76_reg_983 <= add_ln58_76_fu_800_p2;
        trunc_ln42_66_reg_837 <= {{add_ln73_fu_452_p2[24:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_port_reg_data_0_val <= data_0_val;
        ap_port_reg_data_2_val <= data_2_val;
        ap_port_reg_data_3_val <= data_3_val;
        ap_port_reg_data_4_val <= data_4_val;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        data_4_val_read_reg_849 <= ap_port_reg_data_4_val;
        trunc_ln42_67_reg_866 <= {{sub_ln73_4_fu_515_p2[23:10]}};
        trunc_ln42_70_reg_877 <= {{sub_ln73_5_fu_561_p2[24:10]}};
        trunc_ln42_78_reg_887 <= {{grp_fu_144_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce)))) begin
        reg_406 <= {{grp_fu_366_p1[24:10]}};
        reg_418 <= {{grp_fu_146_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce)))) begin
        reg_410 <= {{grp_fu_376_p1[24:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce)))) begin
        reg_414 <= {{grp_fu_147_p2[25:10]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))))) begin
        grp_fu_144_ce = 1'b1;
    end else begin
        grp_fu_144_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_144_p0 = sext_ln70_24_fu_577_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_144_p0 = sext_ln70_25_fu_468_p1;
        end else begin
            grp_fu_144_p0 = 'bx;
        end
    end else begin
        grp_fu_144_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_144_p1 = 25'd33554284;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_144_p1 = 26'd439;
        end else begin
            grp_fu_144_p1 = 'bx;
        end
    end else begin
        grp_fu_144_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))))) begin
        grp_fu_145_ce = 1'b1;
    end else begin
        grp_fu_145_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_145_p0 = sext_ln42_25_fu_620_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_145_p0 = sext_ln70_23_fu_480_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_145_p0 = sext_ln70_21_fu_422_p1;
        end else begin
            grp_fu_145_p0 = 'bx;
        end
    end else begin
        grp_fu_145_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_145_p1 = 26'd541;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_145_p1 = 25'd208;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_145_p1 = 25'd165;
        end else begin
            grp_fu_145_p1 = 'bx;
        end
    end else begin
        grp_fu_145_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))))) begin
        grp_fu_146_ce = 1'b1;
    end else begin
        grp_fu_146_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_146_p0 = sext_ln70_fu_597_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_146_p0 = sext_ln42_23_fu_531_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_146_p0 = sext_ln70_25_fu_468_p1;
        end else begin
            grp_fu_146_p0 = 'bx;
        end
    end else begin
        grp_fu_146_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_146_p1 = 25'd33554253;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_146_p1 = 26'd758;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_146_p1 = 26'd974;
        end else begin
            grp_fu_146_p1 = 'bx;
        end
    end else begin
        grp_fu_146_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))))) begin
        grp_fu_147_ce = 1'b1;
    end else begin
        grp_fu_147_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_147_p0 = sext_ln42_fu_592_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_147_p0 = sext_ln42_23_fu_531_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_147_p0 = sext_ln70_25_fu_468_p1;
        end else begin
            grp_fu_147_p0 = 'bx;
        end
    end else begin
        grp_fu_147_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_147_p1 = 26'd601;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_147_p1 = 26'd368;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_147_p1 = 26'd1194;
        end else begin
            grp_fu_147_p1 = 'bx;
        end
    end else begin
        grp_fu_147_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))))) begin
        grp_fu_148_ce = 1'b1;
    end else begin
        grp_fu_148_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_148_p0 = sext_ln70_fu_597_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_148_p0 = sext_ln70_22_fu_475_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_148_p0 = sext_ln70_21_fu_422_p1;
        end else begin
            grp_fu_148_p0 = 'bx;
        end
    end else begin
        grp_fu_148_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_148_p1 = 25'd33554227;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_148_p1 = 26'd67108403;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_148_p1 = 25'd33554217;
        end else begin
            grp_fu_148_p1 = 'bx;
        end
    end else begin
        grp_fu_148_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_reset_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_61_fu_775_p2 = ($signed(add_ln58_reg_923) + $signed(sext_ln42_16_fu_768_p1));

assign add_ln58_62_fu_730_p2 = ($signed(sext_ln42_24_fu_711_p1) + $signed(sext_ln42_26_fu_714_p1));

assign add_ln58_63_fu_678_p2 = (reg_414 + 16'd74);

assign add_ln58_64_fu_736_p2 = (add_ln58_63_reg_928 + add_ln58_62_fu_730_p2);

assign add_ln58_65_fu_780_p2 = (add_ln58_64_reg_948 + add_ln58_61_fu_775_p2);

assign add_ln58_66_fu_741_p2 = ($signed(sext_ln42_19_fu_700_p1) + $signed(sext_ln42_22_fu_707_p1));

assign add_ln58_67_fu_785_p2 = ($signed(add_ln58_66_reg_953) + $signed(sext_ln42_17_fu_772_p1));

assign add_ln58_68_fu_747_p2 = ($signed(reg_414) + $signed(sext_ln42_27_fu_717_p1));

assign add_ln58_69_fu_684_p2 = (reg_418 + 16'd219);

assign add_ln58_70_fu_753_p2 = (add_ln58_69_reg_933 + add_ln58_68_fu_747_p2);

assign add_ln58_71_fu_790_p2 = (add_ln58_70_reg_958 + add_ln58_67_fu_785_p2);

assign add_ln58_72_fu_758_p2 = ($signed(sext_ln42_20_fu_704_p1) + $signed(trunc_ln42_69_reg_903));

assign add_ln58_73_fu_805_p2 = (add_ln58_72_reg_963 + reg_414);

assign add_ln58_74_fu_795_p2 = (reg_418 + trunc_ln42_75_reg_943);

assign add_ln58_75_fu_763_p2 = (trunc_ln42_78_reg_887 + 16'd27);

assign add_ln58_76_fu_800_p2 = (add_ln58_75_reg_968 + add_ln58_74_fu_795_p2);

assign add_ln58_77_fu_810_p2 = (add_ln58_76_reg_983 + add_ln58_73_fu_805_p2);

assign add_ln58_fu_672_p2 = ($signed(sext_ln42_18_fu_603_p1) + $signed(sext_ln42_21_fu_607_p1));

assign add_ln73_1_fu_656_p2 = ($signed(sext_ln73_10_fu_641_p1) + $signed(sext_ln73_11_fu_652_p1));

assign add_ln73_fu_452_p2 = ($signed(sext_ln73_fu_436_p1) + $signed(sext_ln73_5_fu_448_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return_0 = add_ln58_65_reg_973;

assign ap_return_1 = add_ln58_71_reg_978;

assign ap_return_2 = add_ln58_77_fu_810_p2;

assign grp_fu_366_p1 = grp_fu_145_p2;

assign grp_fu_376_p1 = grp_fu_148_p2;

assign sext_ln42_16_fu_768_p1 = $signed(reg_410);

assign sext_ln42_17_fu_772_p1 = $signed(trunc_ln42_s_reg_938);

assign sext_ln42_18_fu_603_p1 = $signed(reg_406);

assign sext_ln42_19_fu_700_p1 = $signed(reg_410);

assign sext_ln42_20_fu_704_p1 = $signed(trunc_ln42_66_reg_837);

assign sext_ln42_21_fu_607_p1 = $signed(trunc_ln42_67_reg_866);

assign sext_ln42_22_fu_707_p1 = $signed(reg_406);

assign sext_ln42_23_fu_531_p0 = ap_port_reg_data_3_val;

assign sext_ln42_23_fu_531_p1 = sext_ln42_23_fu_531_p0;

assign sext_ln42_24_fu_711_p1 = $signed(trunc_ln42_70_reg_877);

assign sext_ln42_25_fu_620_p1 = data_4_val_read_reg_849;

assign sext_ln42_26_fu_714_p1 = $signed(trunc_ln42_73_reg_913);

assign sext_ln42_27_fu_717_p1 = $signed(trunc_ln42_74_reg_918);

assign sext_ln42_fu_592_p0 = ap_port_reg_data_0_val;

assign sext_ln42_fu_592_p1 = sext_ln42_fu_592_p0;

assign sext_ln70_21_fu_422_p0 = data_1_val;

assign sext_ln70_21_fu_422_p1 = sext_ln70_21_fu_422_p0;

assign sext_ln70_22_fu_475_p0 = ap_port_reg_data_2_val;

assign sext_ln70_22_fu_475_p1 = sext_ln70_22_fu_475_p0;

assign sext_ln70_23_fu_480_p0 = ap_port_reg_data_2_val;

assign sext_ln70_23_fu_480_p1 = sext_ln70_23_fu_480_p0;

assign sext_ln70_24_fu_577_p0 = ap_port_reg_data_4_val;

assign sext_ln70_24_fu_577_p1 = sext_ln70_24_fu_577_p0;

assign sext_ln70_25_fu_468_p1 = $signed(data_5_val);

assign sext_ln70_fu_597_p0 = ap_port_reg_data_0_val;

assign sext_ln70_fu_597_p1 = sext_ln70_fu_597_p0;

assign sext_ln73_10_fu_641_p1 = $signed(shl_ln73_9_fu_634_p3);

assign sext_ln73_11_fu_652_p1 = $signed(shl_ln73_s_fu_645_p3);

assign sext_ln73_5_fu_448_p1 = $signed(shl_ln73_4_fu_440_p3);

assign sext_ln73_6_fu_493_p1 = $signed(shl_ln73_5_fu_485_p3);

assign sext_ln73_7_fu_511_p1 = $signed(shl_ln73_6_fu_503_p3);

assign sext_ln73_8_fu_545_p1 = $signed(shl_ln73_7_fu_537_p3);

assign sext_ln73_9_fu_557_p1 = $signed(shl_ln73_8_fu_549_p3);

assign sext_ln73_fu_436_p1 = $signed(shl_ln_fu_428_p3);

assign shl_ln73_4_fu_440_p1 = data_1_val;

assign shl_ln73_4_fu_440_p3 = {{shl_ln73_4_fu_440_p1}, {6'd0}};

assign shl_ln73_5_fu_485_p1 = ap_port_reg_data_2_val;

assign shl_ln73_5_fu_485_p3 = {{shl_ln73_5_fu_485_p1}, {7'd0}};

assign shl_ln73_6_fu_503_p1 = ap_port_reg_data_2_val;

assign shl_ln73_6_fu_503_p3 = {{shl_ln73_6_fu_503_p1}, {1'd0}};

assign shl_ln73_7_fu_537_p1 = ap_port_reg_data_3_val;

assign shl_ln73_7_fu_537_p3 = {{shl_ln73_7_fu_537_p1}, {8'd0}};

assign shl_ln73_8_fu_549_p1 = ap_port_reg_data_3_val;

assign shl_ln73_8_fu_549_p3 = {{shl_ln73_8_fu_549_p1}, {2'd0}};

assign shl_ln73_9_fu_634_p3 = {{data_4_val_read_reg_849}, {6'd0}};

assign shl_ln73_s_fu_645_p3 = {{data_4_val_read_reg_849}, {3'd0}};

assign shl_ln_fu_428_p1 = data_1_val;

assign shl_ln_fu_428_p3 = {{shl_ln_fu_428_p1}, {8'd0}};

assign sub_ln73_4_fu_515_p2 = ($signed(sub_ln73_fu_497_p2) - $signed(sext_ln73_7_fu_511_p1));

assign sub_ln73_5_fu_561_p2 = ($signed(sext_ln73_8_fu_545_p1) - $signed(sext_ln73_9_fu_557_p1));

assign sub_ln73_fu_497_p2 = ($signed(24'd0) - $signed(sext_ln73_6_fu_493_p1));

assign trunc_ln42_73_fu_624_p1 = grp_fu_144_p2;

assign trunc_ln42_s_fu_690_p1 = grp_fu_146_p2;

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s
